package com.github.kyrenesjtv.springboot2.springboot2_withsecurity.springboot2_withsecurity.entity.po;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.github.kyrenesjtv.springboot2.springboot2_withsecurity.springboot2_withsecurity.util.StringUtil;
import org.springframework.format.annotation.DateTimeFormat;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class UserPO extends UserBaseBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.id
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.address
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.birthday
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    @DateTimeFormat(pattern ="yyyy-MM-dd HH:mm:ss")
    private Date birthday;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.idCard
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.email
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.fax
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.ip
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.post
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private Long post;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.loginCount
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private Long loginCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.loginName
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.loginTime
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    @DateTimeFormat(pattern ="yyyy-MM-dd HH:mm:ss")
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.mobile
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.name
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.nick
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private String nick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.remarks
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.password
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.picture
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.zipCode
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.regdate
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    @DateTimeFormat(pattern ="yyyy-MM-dd HH:mm:ss")
    private Date regdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.sex
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private Long sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.shortString
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private String shortString;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.sort
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private Long sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.state
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private Long state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.telephone
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.departId
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private String departId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.createDate
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    @DateTimeFormat(pattern ="yyyy-MM-dd HH:mm:ss")
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.createId
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private String createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_user.createName
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    private String createName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.id
     *
     * @return the value of global_user.id
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.id
     *
     * @param id the value for global_user.id
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.address
     *
     * @return the value of global_user.address
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.address
     *
     * @param address the value for global_user.address
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.birthday
     *
     * @return the value of global_user.birthday
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.birthday
     *
     * @param birthday the value for global_user.birthday
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setBirthday(String birthday) throws ParseException {
        if (StringUtil.isEmpty(birthday)) {
            this.createDate = null;
        }else {
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            this.createDate = formatter.parse(birthday);
        }
//        this.birthday = birthday;
    }

    public void setBirthday(Date birthday) {
//        if (StringUtil.isEmpty(birthday)) {
//            this.createDate = null;
//        }else {
//            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
//            this.createDate = formatter.parse(birthday);
//        }
                this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.idCard
     *
     * @return the value of global_user.idCard
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.idCard
     *
     * @param idCard the value for global_user.idCard
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.email
     *
     * @return the value of global_user.email
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.email
     *
     * @param email the value for global_user.email
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.fax
     *
     * @return the value of global_user.fax
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.fax
     *
     * @param fax the value for global_user.fax
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.ip
     *
     * @return the value of global_user.ip
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.ip
     *
     * @param ip the value for global_user.ip
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.post
     *
     * @return the value of global_user.post
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public Long getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.post
     *
     * @param post the value for global_user.post
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setPost(Long post) {
        this.post = post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.loginCount
     *
     * @return the value of global_user.loginCount
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public Long getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.loginCount
     *
     * @param loginCount the value for global_user.loginCount
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setLoginCount(Long loginCount) {
        this.loginCount = loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.loginName
     *
     * @return the value of global_user.loginName
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.loginName
     *
     * @param loginName the value for global_user.loginName
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.loginTime
     *
     * @return the value of global_user.loginTime
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.loginTime
     *
     * @param loginTime the value for global_user.loginTime
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.mobile
     *
     * @return the value of global_user.mobile
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.mobile
     *
     * @param mobile the value for global_user.mobile
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.name
     *
     * @return the value of global_user.name
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.name
     *
     * @param name the value for global_user.name
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.nick
     *
     * @return the value of global_user.nick
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.nick
     *
     * @param nick the value for global_user.nick
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setNick(String nick) {
        this.nick = nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.remarks
     *
     * @return the value of global_user.remarks
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.remarks
     *
     * @param remarks the value for global_user.remarks
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.password
     *
     * @return the value of global_user.password
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.password
     *
     * @param password the value for global_user.password
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.picture
     *
     * @return the value of global_user.picture
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.picture
     *
     * @param picture the value for global_user.picture
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.zipCode
     *
     * @return the value of global_user.zipCode
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.zipCode
     *
     * @param zipCode the value for global_user.zipCode
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.regdate
     *
     * @return the value of global_user.regdate
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public Date getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.regdate
     *
     * @param regdate the value for global_user.regdate
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.sex
     *
     * @return the value of global_user.sex
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public Long getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.sex
     *
     * @param sex the value for global_user.sex
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setSex(Long sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.shortString
     *
     * @return the value of global_user.shortString
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public String getShortString() {
        return shortString;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.shortString
     *
     * @param shortString the value for global_user.shortString
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setShortString(String shortString) {
        this.shortString = shortString;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.sort
     *
     * @return the value of global_user.sort
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.sort
     *
     * @param sort the value for global_user.sort
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.state
     *
     * @return the value of global_user.state
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public Long getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.state
     *
     * @param state the value for global_user.state
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setState(Long state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.telephone
     *
     * @return the value of global_user.telephone
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.telephone
     *
     * @param telephone the value for global_user.telephone
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.departId
     *
     * @return the value of global_user.departId
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public String getDepartId() {
        return departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.departId
     *
     * @param departId the value for global_user.departId
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setDepartId(String departId) {
        this.departId = departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.createDate
     *
     * @return the value of global_user.createDate
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.createDate
     *
     * @param createDate the value for global_user.createDate
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.createId
     *
     * @return the value of global_user.createId
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.createId
     *
     * @param createId the value for global_user.createId
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setCreateId(String createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_user.createName
     *
     * @return the value of global_user.createName
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_user.createName
     *
     * @param createName the value for global_user.createName
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    public void setCreateName(String createName) {
        this.createName = createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_user
     *
     * @mbggenerated Mon Mar 18 14:19:37 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", address=").append(address);
        sb.append(", birthday=").append(birthday);
        sb.append(", idCard=").append(idCard);
        sb.append(", email=").append(email);
        sb.append(", fax=").append(fax);
        sb.append(", ip=").append(ip);
        sb.append(", post=").append(post);
        sb.append(", loginCount=").append(loginCount);
        sb.append(", loginName=").append(loginName);
        sb.append(", loginTime=").append(loginTime);
        sb.append(", mobile=").append(mobile);
        sb.append(", name=").append(name);
        sb.append(", nick=").append(nick);
        sb.append(", remarks=").append(remarks);
        sb.append(", password=").append(password);
        sb.append(", picture=").append(picture);
        sb.append(", zipCode=").append(zipCode);
        sb.append(", regdate=").append(regdate);
        sb.append(", sex=").append(sex);
        sb.append(", shortString=").append(shortString);
        sb.append(", sort=").append(sort);
        sb.append(", state=").append(state);
        sb.append(", telephone=").append(telephone);
        sb.append(", departId=").append(departId);
        sb.append(", createDate=").append(createDate);
        sb.append(", createId=").append(createId);
        sb.append(", createName=").append(createName);
        sb.append("]");
        return sb.toString();
    }
}