package com.github.kyrenesjtv.springboot2.springboot2_withsql.po;

import java.util.Date;

public class MonCarDakaInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.driver_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer driver_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.user_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.driver_money
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double driver_money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.user_money
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double user_money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.dpet_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer dpet_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.car_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer car_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.daka_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer daka_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.shoufei_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date shoufei_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.shoufei_time_
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date shoufei_time_;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.danjia_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double danjia_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.licheng
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double licheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.weizhang
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String weizhang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.is_flag
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer is_flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.remark
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.car_address_daka
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String car_address_daka;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.car_destination_daka
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String car_destination_daka;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.car_youhao
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double car_youhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.yong_che_ren
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String yong_che_ren;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.fy_apply_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer fy_apply_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.feiyong
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double feiyong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.xiaoshi
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double xiaoshi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.jichu
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double jichu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.fujia
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double fujia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.xingshi_km
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double xingshi_km;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.feiyong_zhiyi
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String feiyong_zhiyi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.yong_che_times
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String yong_che_times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.city_code
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String city_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.old_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Long old_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_daka_info.syna_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date syna_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.id
     *
     * @return the value of mon_car_daka_info.id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.id
     *
     * @param id the value for mon_car_daka_info.id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.driver_id
     *
     * @return the value of mon_car_daka_info.driver_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getDriver_id() {
        return driver_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.driver_id
     *
     * @param driver_id the value for mon_car_daka_info.driver_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDriver_id(Integer driver_id) {
        this.driver_id = driver_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.user_id
     *
     * @return the value of mon_car_daka_info.user_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.user_id
     *
     * @param user_id the value for mon_car_daka_info.user_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.driver_money
     *
     * @return the value of mon_car_daka_info.driver_money
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getDriver_money() {
        return driver_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.driver_money
     *
     * @param driver_money the value for mon_car_daka_info.driver_money
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDriver_money(Double driver_money) {
        this.driver_money = driver_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.user_money
     *
     * @return the value of mon_car_daka_info.user_money
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getUser_money() {
        return user_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.user_money
     *
     * @param user_money the value for mon_car_daka_info.user_money
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setUser_money(Double user_money) {
        this.user_money = user_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.dpet_id
     *
     * @return the value of mon_car_daka_info.dpet_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getDpet_id() {
        return dpet_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.dpet_id
     *
     * @param dpet_id the value for mon_car_daka_info.dpet_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDpet_id(Integer dpet_id) {
        this.dpet_id = dpet_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.car_id
     *
     * @return the value of mon_car_daka_info.car_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getCar_id() {
        return car_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.car_id
     *
     * @param car_id the value for mon_car_daka_info.car_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_id(Integer car_id) {
        this.car_id = car_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.daka_id
     *
     * @return the value of mon_car_daka_info.daka_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getDaka_id() {
        return daka_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.daka_id
     *
     * @param daka_id the value for mon_car_daka_info.daka_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDaka_id(Integer daka_id) {
        this.daka_id = daka_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.shoufei_time
     *
     * @return the value of mon_car_daka_info.shoufei_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getShoufei_time() {
        return shoufei_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.shoufei_time
     *
     * @param shoufei_time the value for mon_car_daka_info.shoufei_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setShoufei_time(Date shoufei_time) {
        this.shoufei_time = shoufei_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.shoufei_time_
     *
     * @return the value of mon_car_daka_info.shoufei_time_
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getShoufei_time_() {
        return shoufei_time_;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.shoufei_time_
     *
     * @param shoufei_time_ the value for mon_car_daka_info.shoufei_time_
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setShoufei_time_(Date shoufei_time_) {
        this.shoufei_time_ = shoufei_time_;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.danjia_id
     *
     * @return the value of mon_car_daka_info.danjia_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getDanjia_id() {
        return danjia_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.danjia_id
     *
     * @param danjia_id the value for mon_car_daka_info.danjia_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDanjia_id(Double danjia_id) {
        this.danjia_id = danjia_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.licheng
     *
     * @return the value of mon_car_daka_info.licheng
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getLicheng() {
        return licheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.licheng
     *
     * @param licheng the value for mon_car_daka_info.licheng
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setLicheng(Double licheng) {
        this.licheng = licheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.weizhang
     *
     * @return the value of mon_car_daka_info.weizhang
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getWeizhang() {
        return weizhang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.weizhang
     *
     * @param weizhang the value for mon_car_daka_info.weizhang
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setWeizhang(String weizhang) {
        this.weizhang = weizhang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.is_flag
     *
     * @return the value of mon_car_daka_info.is_flag
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getIs_flag() {
        return is_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.is_flag
     *
     * @param is_flag the value for mon_car_daka_info.is_flag
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setIs_flag(Integer is_flag) {
        this.is_flag = is_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.remark
     *
     * @return the value of mon_car_daka_info.remark
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.remark
     *
     * @param remark the value for mon_car_daka_info.remark
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.car_address_daka
     *
     * @return the value of mon_car_daka_info.car_address_daka
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCar_address_daka() {
        return car_address_daka;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.car_address_daka
     *
     * @param car_address_daka the value for mon_car_daka_info.car_address_daka
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_address_daka(String car_address_daka) {
        this.car_address_daka = car_address_daka;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.car_destination_daka
     *
     * @return the value of mon_car_daka_info.car_destination_daka
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCar_destination_daka() {
        return car_destination_daka;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.car_destination_daka
     *
     * @param car_destination_daka the value for mon_car_daka_info.car_destination_daka
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_destination_daka(String car_destination_daka) {
        this.car_destination_daka = car_destination_daka;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.car_youhao
     *
     * @return the value of mon_car_daka_info.car_youhao
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getCar_youhao() {
        return car_youhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.car_youhao
     *
     * @param car_youhao the value for mon_car_daka_info.car_youhao
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_youhao(Double car_youhao) {
        this.car_youhao = car_youhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.yong_che_ren
     *
     * @return the value of mon_car_daka_info.yong_che_ren
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getYong_che_ren() {
        return yong_che_ren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.yong_che_ren
     *
     * @param yong_che_ren the value for mon_car_daka_info.yong_che_ren
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setYong_che_ren(String yong_che_ren) {
        this.yong_che_ren = yong_che_ren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.fy_apply_id
     *
     * @return the value of mon_car_daka_info.fy_apply_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getFy_apply_id() {
        return fy_apply_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.fy_apply_id
     *
     * @param fy_apply_id the value for mon_car_daka_info.fy_apply_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setFy_apply_id(Integer fy_apply_id) {
        this.fy_apply_id = fy_apply_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.feiyong
     *
     * @return the value of mon_car_daka_info.feiyong
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getFeiyong() {
        return feiyong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.feiyong
     *
     * @param feiyong the value for mon_car_daka_info.feiyong
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setFeiyong(Double feiyong) {
        this.feiyong = feiyong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.xiaoshi
     *
     * @return the value of mon_car_daka_info.xiaoshi
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getXiaoshi() {
        return xiaoshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.xiaoshi
     *
     * @param xiaoshi the value for mon_car_daka_info.xiaoshi
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setXiaoshi(Double xiaoshi) {
        this.xiaoshi = xiaoshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.jichu
     *
     * @return the value of mon_car_daka_info.jichu
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getJichu() {
        return jichu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.jichu
     *
     * @param jichu the value for mon_car_daka_info.jichu
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setJichu(Double jichu) {
        this.jichu = jichu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.fujia
     *
     * @return the value of mon_car_daka_info.fujia
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getFujia() {
        return fujia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.fujia
     *
     * @param fujia the value for mon_car_daka_info.fujia
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setFujia(Double fujia) {
        this.fujia = fujia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.xingshi_km
     *
     * @return the value of mon_car_daka_info.xingshi_km
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getXingshi_km() {
        return xingshi_km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.xingshi_km
     *
     * @param xingshi_km the value for mon_car_daka_info.xingshi_km
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setXingshi_km(Double xingshi_km) {
        this.xingshi_km = xingshi_km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.feiyong_zhiyi
     *
     * @return the value of mon_car_daka_info.feiyong_zhiyi
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getFeiyong_zhiyi() {
        return feiyong_zhiyi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.feiyong_zhiyi
     *
     * @param feiyong_zhiyi the value for mon_car_daka_info.feiyong_zhiyi
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setFeiyong_zhiyi(String feiyong_zhiyi) {
        this.feiyong_zhiyi = feiyong_zhiyi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.yong_che_times
     *
     * @return the value of mon_car_daka_info.yong_che_times
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getYong_che_times() {
        return yong_che_times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.yong_che_times
     *
     * @param yong_che_times the value for mon_car_daka_info.yong_che_times
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setYong_che_times(String yong_che_times) {
        this.yong_che_times = yong_che_times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.city_code
     *
     * @return the value of mon_car_daka_info.city_code
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCity_code() {
        return city_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.city_code
     *
     * @param city_code the value for mon_car_daka_info.city_code
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCity_code(String city_code) {
        this.city_code = city_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.old_id
     *
     * @return the value of mon_car_daka_info.old_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Long getOld_id() {
        return old_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.old_id
     *
     * @param old_id the value for mon_car_daka_info.old_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setOld_id(Long old_id) {
        this.old_id = old_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_daka_info.syna_time
     *
     * @return the value of mon_car_daka_info.syna_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getSyna_time() {
        return syna_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_daka_info.syna_time
     *
     * @param syna_time the value for mon_car_daka_info.syna_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setSyna_time(Date syna_time) {
        this.syna_time = syna_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_daka_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", driver_id=").append(driver_id);
        sb.append(", user_id=").append(user_id);
        sb.append(", driver_money=").append(driver_money);
        sb.append(", user_money=").append(user_money);
        sb.append(", dpet_id=").append(dpet_id);
        sb.append(", car_id=").append(car_id);
        sb.append(", daka_id=").append(daka_id);
        sb.append(", shoufei_time=").append(shoufei_time);
        sb.append(", shoufei_time_=").append(shoufei_time_);
        sb.append(", danjia_id=").append(danjia_id);
        sb.append(", licheng=").append(licheng);
        sb.append(", weizhang=").append(weizhang);
        sb.append(", is_flag=").append(is_flag);
        sb.append(", remark=").append(remark);
        sb.append(", car_address_daka=").append(car_address_daka);
        sb.append(", car_destination_daka=").append(car_destination_daka);
        sb.append(", car_youhao=").append(car_youhao);
        sb.append(", yong_che_ren=").append(yong_che_ren);
        sb.append(", fy_apply_id=").append(fy_apply_id);
        sb.append(", feiyong=").append(feiyong);
        sb.append(", xiaoshi=").append(xiaoshi);
        sb.append(", jichu=").append(jichu);
        sb.append(", fujia=").append(fujia);
        sb.append(", xingshi_km=").append(xingshi_km);
        sb.append(", feiyong_zhiyi=").append(feiyong_zhiyi);
        sb.append(", yong_che_times=").append(yong_che_times);
        sb.append(", city_code=").append(city_code);
        sb.append(", old_id=").append(old_id);
        sb.append(", syna_time=").append(syna_time);
        sb.append("]");
        return sb.toString();
    }
}