package com.github.kyrenesjtv.springboot2.springboot2_withsql.po;

import java.util.Date;

public class MonCarInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String car_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_number
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer car_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer car_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_model
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer car_model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_state
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer car_state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.department_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer department_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_manufacturers
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String car_manufacturers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_milage
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double car_milage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_icon
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String car_icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_tree_icon
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String car_tree_icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_color
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer car_color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_capacity
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double car_capacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.past_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer past_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.add_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String add_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_price
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double car_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.license_plate_color
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String license_plate_color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_login
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer car_login;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.img_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String img_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.img_save_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String img_save_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.is_flag
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer is_flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_remark
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String car_remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_employState
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer car_employState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_seating
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer car_seating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_xsz
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String car_xsz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_money
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double car_money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_vin
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer car_vin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_pl
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String car_pl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_zg
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer car_zg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_zb
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer car_zb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_ts
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer car_ts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_chegai
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer car_chegai;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_speed
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double car_speed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_guige_xinghao
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String car_guige_xinghao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_xingzhi
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer car_xingzhi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_zichankahao
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String car_zichankahao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_youliao_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer car_youliao_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_cj_number
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String car_cj_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_fdj_number
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String car_fdj_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_baoyangT
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer car_baoyangT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.chedui
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String chedui;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.serial_number
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String serial_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.drive_mode
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String drive_mode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_license_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date car_license_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.power
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String power;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.oil_consumption
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String oil_consumption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_register_number
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String car_register_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_register_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date car_register_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_fdj_model
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String car_fdj_model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.additional_tax_number
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String additional_tax_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.scrap_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date scrap_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.safety_km
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String safety_km;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.source_country
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String source_country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.fuel_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String fuel_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.swerve_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String swerve_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.tyre_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer tyre_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.tyre_distance
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String tyre_distance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.tyre_standard
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String tyre_standard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.axle_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer axle_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.axle_distance
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String axle_distance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.out_size
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String out_size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.total_quality
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String total_quality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.get_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String get_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.leave_factory_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date leave_factory_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.certificate_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date certificate_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.yearinspect_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date yearinspect_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_img_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String car_img_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.car_img_path
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String car_img_path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.borrow_dept
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String borrow_dept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.skill_state
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer skill_state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.wifi_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String wifi_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.syna_flag
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String syna_flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.city_code
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String city_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.old_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Long old_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_info.syna_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date syna_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.id
     *
     * @return the value of mon_car_info.id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.id
     *
     * @param id the value for mon_car_info.id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_num
     *
     * @return the value of mon_car_info.car_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCar_num() {
        return car_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_num
     *
     * @param car_num the value for mon_car_info.car_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_num(String car_num) {
        this.car_num = car_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_number
     *
     * @return the value of mon_car_info.car_number
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getCar_number() {
        return car_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_number
     *
     * @param car_number the value for mon_car_info.car_number
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_number(Integer car_number) {
        this.car_number = car_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_type
     *
     * @return the value of mon_car_info.car_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getCar_type() {
        return car_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_type
     *
     * @param car_type the value for mon_car_info.car_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_type(Integer car_type) {
        this.car_type = car_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_model
     *
     * @return the value of mon_car_info.car_model
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getCar_model() {
        return car_model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_model
     *
     * @param car_model the value for mon_car_info.car_model
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_model(Integer car_model) {
        this.car_model = car_model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_state
     *
     * @return the value of mon_car_info.car_state
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getCar_state() {
        return car_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_state
     *
     * @param car_state the value for mon_car_info.car_state
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_state(Integer car_state) {
        this.car_state = car_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.department_id
     *
     * @return the value of mon_car_info.department_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getDepartment_id() {
        return department_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.department_id
     *
     * @param department_id the value for mon_car_info.department_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDepartment_id(Integer department_id) {
        this.department_id = department_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_manufacturers
     *
     * @return the value of mon_car_info.car_manufacturers
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCar_manufacturers() {
        return car_manufacturers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_manufacturers
     *
     * @param car_manufacturers the value for mon_car_info.car_manufacturers
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_manufacturers(String car_manufacturers) {
        this.car_manufacturers = car_manufacturers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_milage
     *
     * @return the value of mon_car_info.car_milage
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getCar_milage() {
        return car_milage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_milage
     *
     * @param car_milage the value for mon_car_info.car_milage
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_milage(Double car_milage) {
        this.car_milage = car_milage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_icon
     *
     * @return the value of mon_car_info.car_icon
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCar_icon() {
        return car_icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_icon
     *
     * @param car_icon the value for mon_car_info.car_icon
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_icon(String car_icon) {
        this.car_icon = car_icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_tree_icon
     *
     * @return the value of mon_car_info.car_tree_icon
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCar_tree_icon() {
        return car_tree_icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_tree_icon
     *
     * @param car_tree_icon the value for mon_car_info.car_tree_icon
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_tree_icon(String car_tree_icon) {
        this.car_tree_icon = car_tree_icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_color
     *
     * @return the value of mon_car_info.car_color
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getCar_color() {
        return car_color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_color
     *
     * @param car_color the value for mon_car_info.car_color
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_color(Integer car_color) {
        this.car_color = car_color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_capacity
     *
     * @return the value of mon_car_info.car_capacity
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getCar_capacity() {
        return car_capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_capacity
     *
     * @param car_capacity the value for mon_car_info.car_capacity
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_capacity(Double car_capacity) {
        this.car_capacity = car_capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.past_time
     *
     * @return the value of mon_car_info.past_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getPast_time() {
        return past_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.past_time
     *
     * @param past_time the value for mon_car_info.past_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setPast_time(Integer past_time) {
        this.past_time = past_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.add_time
     *
     * @return the value of mon_car_info.add_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getAdd_time() {
        return add_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.add_time
     *
     * @param add_time the value for mon_car_info.add_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setAdd_time(String add_time) {
        this.add_time = add_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_price
     *
     * @return the value of mon_car_info.car_price
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getCar_price() {
        return car_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_price
     *
     * @param car_price the value for mon_car_info.car_price
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_price(Double car_price) {
        this.car_price = car_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.license_plate_color
     *
     * @return the value of mon_car_info.license_plate_color
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getLicense_plate_color() {
        return license_plate_color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.license_plate_color
     *
     * @param license_plate_color the value for mon_car_info.license_plate_color
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setLicense_plate_color(String license_plate_color) {
        this.license_plate_color = license_plate_color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_login
     *
     * @return the value of mon_car_info.car_login
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getCar_login() {
        return car_login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_login
     *
     * @param car_login the value for mon_car_info.car_login
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_login(Integer car_login) {
        this.car_login = car_login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.img_name
     *
     * @return the value of mon_car_info.img_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getImg_name() {
        return img_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.img_name
     *
     * @param img_name the value for mon_car_info.img_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setImg_name(String img_name) {
        this.img_name = img_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.img_save_name
     *
     * @return the value of mon_car_info.img_save_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getImg_save_name() {
        return img_save_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.img_save_name
     *
     * @param img_save_name the value for mon_car_info.img_save_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setImg_save_name(String img_save_name) {
        this.img_save_name = img_save_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.is_flag
     *
     * @return the value of mon_car_info.is_flag
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getIs_flag() {
        return is_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.is_flag
     *
     * @param is_flag the value for mon_car_info.is_flag
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setIs_flag(Integer is_flag) {
        this.is_flag = is_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_remark
     *
     * @return the value of mon_car_info.car_remark
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCar_remark() {
        return car_remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_remark
     *
     * @param car_remark the value for mon_car_info.car_remark
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_remark(String car_remark) {
        this.car_remark = car_remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_employState
     *
     * @return the value of mon_car_info.car_employState
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getCar_employState() {
        return car_employState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_employState
     *
     * @param car_employState the value for mon_car_info.car_employState
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_employState(Integer car_employState) {
        this.car_employState = car_employState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_seating
     *
     * @return the value of mon_car_info.car_seating
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getCar_seating() {
        return car_seating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_seating
     *
     * @param car_seating the value for mon_car_info.car_seating
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_seating(Integer car_seating) {
        this.car_seating = car_seating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_xsz
     *
     * @return the value of mon_car_info.car_xsz
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCar_xsz() {
        return car_xsz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_xsz
     *
     * @param car_xsz the value for mon_car_info.car_xsz
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_xsz(String car_xsz) {
        this.car_xsz = car_xsz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_money
     *
     * @return the value of mon_car_info.car_money
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getCar_money() {
        return car_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_money
     *
     * @param car_money the value for mon_car_info.car_money
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_money(Double car_money) {
        this.car_money = car_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_vin
     *
     * @return the value of mon_car_info.car_vin
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getCar_vin() {
        return car_vin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_vin
     *
     * @param car_vin the value for mon_car_info.car_vin
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_vin(Integer car_vin) {
        this.car_vin = car_vin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_pl
     *
     * @return the value of mon_car_info.car_pl
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCar_pl() {
        return car_pl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_pl
     *
     * @param car_pl the value for mon_car_info.car_pl
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_pl(String car_pl) {
        this.car_pl = car_pl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_zg
     *
     * @return the value of mon_car_info.car_zg
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getCar_zg() {
        return car_zg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_zg
     *
     * @param car_zg the value for mon_car_info.car_zg
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_zg(Integer car_zg) {
        this.car_zg = car_zg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_zb
     *
     * @return the value of mon_car_info.car_zb
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getCar_zb() {
        return car_zb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_zb
     *
     * @param car_zb the value for mon_car_info.car_zb
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_zb(Integer car_zb) {
        this.car_zb = car_zb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_ts
     *
     * @return the value of mon_car_info.car_ts
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getCar_ts() {
        return car_ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_ts
     *
     * @param car_ts the value for mon_car_info.car_ts
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_ts(Integer car_ts) {
        this.car_ts = car_ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_chegai
     *
     * @return the value of mon_car_info.car_chegai
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getCar_chegai() {
        return car_chegai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_chegai
     *
     * @param car_chegai the value for mon_car_info.car_chegai
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_chegai(Integer car_chegai) {
        this.car_chegai = car_chegai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_speed
     *
     * @return the value of mon_car_info.car_speed
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getCar_speed() {
        return car_speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_speed
     *
     * @param car_speed the value for mon_car_info.car_speed
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_speed(Double car_speed) {
        this.car_speed = car_speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_guige_xinghao
     *
     * @return the value of mon_car_info.car_guige_xinghao
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCar_guige_xinghao() {
        return car_guige_xinghao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_guige_xinghao
     *
     * @param car_guige_xinghao the value for mon_car_info.car_guige_xinghao
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_guige_xinghao(String car_guige_xinghao) {
        this.car_guige_xinghao = car_guige_xinghao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_xingzhi
     *
     * @return the value of mon_car_info.car_xingzhi
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getCar_xingzhi() {
        return car_xingzhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_xingzhi
     *
     * @param car_xingzhi the value for mon_car_info.car_xingzhi
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_xingzhi(Integer car_xingzhi) {
        this.car_xingzhi = car_xingzhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_zichankahao
     *
     * @return the value of mon_car_info.car_zichankahao
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCar_zichankahao() {
        return car_zichankahao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_zichankahao
     *
     * @param car_zichankahao the value for mon_car_info.car_zichankahao
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_zichankahao(String car_zichankahao) {
        this.car_zichankahao = car_zichankahao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_youliao_type
     *
     * @return the value of mon_car_info.car_youliao_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getCar_youliao_type() {
        return car_youliao_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_youliao_type
     *
     * @param car_youliao_type the value for mon_car_info.car_youliao_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_youliao_type(Integer car_youliao_type) {
        this.car_youliao_type = car_youliao_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_cj_number
     *
     * @return the value of mon_car_info.car_cj_number
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCar_cj_number() {
        return car_cj_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_cj_number
     *
     * @param car_cj_number the value for mon_car_info.car_cj_number
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_cj_number(String car_cj_number) {
        this.car_cj_number = car_cj_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_fdj_number
     *
     * @return the value of mon_car_info.car_fdj_number
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCar_fdj_number() {
        return car_fdj_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_fdj_number
     *
     * @param car_fdj_number the value for mon_car_info.car_fdj_number
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_fdj_number(String car_fdj_number) {
        this.car_fdj_number = car_fdj_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_baoyangT
     *
     * @return the value of mon_car_info.car_baoyangT
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getCar_baoyangT() {
        return car_baoyangT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_baoyangT
     *
     * @param car_baoyangT the value for mon_car_info.car_baoyangT
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_baoyangT(Integer car_baoyangT) {
        this.car_baoyangT = car_baoyangT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.chedui
     *
     * @return the value of mon_car_info.chedui
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getChedui() {
        return chedui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.chedui
     *
     * @param chedui the value for mon_car_info.chedui
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setChedui(String chedui) {
        this.chedui = chedui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.serial_number
     *
     * @return the value of mon_car_info.serial_number
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getSerial_number() {
        return serial_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.serial_number
     *
     * @param serial_number the value for mon_car_info.serial_number
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setSerial_number(String serial_number) {
        this.serial_number = serial_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.drive_mode
     *
     * @return the value of mon_car_info.drive_mode
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getDrive_mode() {
        return drive_mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.drive_mode
     *
     * @param drive_mode the value for mon_car_info.drive_mode
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDrive_mode(String drive_mode) {
        this.drive_mode = drive_mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_license_time
     *
     * @return the value of mon_car_info.car_license_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getCar_license_time() {
        return car_license_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_license_time
     *
     * @param car_license_time the value for mon_car_info.car_license_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_license_time(Date car_license_time) {
        this.car_license_time = car_license_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.power
     *
     * @return the value of mon_car_info.power
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.power
     *
     * @param power the value for mon_car_info.power
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setPower(String power) {
        this.power = power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.oil_consumption
     *
     * @return the value of mon_car_info.oil_consumption
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getOil_consumption() {
        return oil_consumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.oil_consumption
     *
     * @param oil_consumption the value for mon_car_info.oil_consumption
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setOil_consumption(String oil_consumption) {
        this.oil_consumption = oil_consumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_register_number
     *
     * @return the value of mon_car_info.car_register_number
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCar_register_number() {
        return car_register_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_register_number
     *
     * @param car_register_number the value for mon_car_info.car_register_number
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_register_number(String car_register_number) {
        this.car_register_number = car_register_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_register_time
     *
     * @return the value of mon_car_info.car_register_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getCar_register_time() {
        return car_register_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_register_time
     *
     * @param car_register_time the value for mon_car_info.car_register_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_register_time(Date car_register_time) {
        this.car_register_time = car_register_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_fdj_model
     *
     * @return the value of mon_car_info.car_fdj_model
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCar_fdj_model() {
        return car_fdj_model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_fdj_model
     *
     * @param car_fdj_model the value for mon_car_info.car_fdj_model
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_fdj_model(String car_fdj_model) {
        this.car_fdj_model = car_fdj_model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.additional_tax_number
     *
     * @return the value of mon_car_info.additional_tax_number
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getAdditional_tax_number() {
        return additional_tax_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.additional_tax_number
     *
     * @param additional_tax_number the value for mon_car_info.additional_tax_number
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setAdditional_tax_number(String additional_tax_number) {
        this.additional_tax_number = additional_tax_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.scrap_time
     *
     * @return the value of mon_car_info.scrap_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getScrap_time() {
        return scrap_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.scrap_time
     *
     * @param scrap_time the value for mon_car_info.scrap_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setScrap_time(Date scrap_time) {
        this.scrap_time = scrap_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.safety_km
     *
     * @return the value of mon_car_info.safety_km
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getSafety_km() {
        return safety_km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.safety_km
     *
     * @param safety_km the value for mon_car_info.safety_km
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setSafety_km(String safety_km) {
        this.safety_km = safety_km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.source_country
     *
     * @return the value of mon_car_info.source_country
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getSource_country() {
        return source_country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.source_country
     *
     * @param source_country the value for mon_car_info.source_country
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setSource_country(String source_country) {
        this.source_country = source_country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.fuel_type
     *
     * @return the value of mon_car_info.fuel_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getFuel_type() {
        return fuel_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.fuel_type
     *
     * @param fuel_type the value for mon_car_info.fuel_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setFuel_type(String fuel_type) {
        this.fuel_type = fuel_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.swerve_type
     *
     * @return the value of mon_car_info.swerve_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getSwerve_type() {
        return swerve_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.swerve_type
     *
     * @param swerve_type the value for mon_car_info.swerve_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setSwerve_type(String swerve_type) {
        this.swerve_type = swerve_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.tyre_num
     *
     * @return the value of mon_car_info.tyre_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getTyre_num() {
        return tyre_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.tyre_num
     *
     * @param tyre_num the value for mon_car_info.tyre_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setTyre_num(Integer tyre_num) {
        this.tyre_num = tyre_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.tyre_distance
     *
     * @return the value of mon_car_info.tyre_distance
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getTyre_distance() {
        return tyre_distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.tyre_distance
     *
     * @param tyre_distance the value for mon_car_info.tyre_distance
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setTyre_distance(String tyre_distance) {
        this.tyre_distance = tyre_distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.tyre_standard
     *
     * @return the value of mon_car_info.tyre_standard
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getTyre_standard() {
        return tyre_standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.tyre_standard
     *
     * @param tyre_standard the value for mon_car_info.tyre_standard
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setTyre_standard(String tyre_standard) {
        this.tyre_standard = tyre_standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.axle_num
     *
     * @return the value of mon_car_info.axle_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getAxle_num() {
        return axle_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.axle_num
     *
     * @param axle_num the value for mon_car_info.axle_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setAxle_num(Integer axle_num) {
        this.axle_num = axle_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.axle_distance
     *
     * @return the value of mon_car_info.axle_distance
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getAxle_distance() {
        return axle_distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.axle_distance
     *
     * @param axle_distance the value for mon_car_info.axle_distance
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setAxle_distance(String axle_distance) {
        this.axle_distance = axle_distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.out_size
     *
     * @return the value of mon_car_info.out_size
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getOut_size() {
        return out_size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.out_size
     *
     * @param out_size the value for mon_car_info.out_size
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setOut_size(String out_size) {
        this.out_size = out_size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.total_quality
     *
     * @return the value of mon_car_info.total_quality
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getTotal_quality() {
        return total_quality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.total_quality
     *
     * @param total_quality the value for mon_car_info.total_quality
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setTotal_quality(String total_quality) {
        this.total_quality = total_quality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.get_type
     *
     * @return the value of mon_car_info.get_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getGet_type() {
        return get_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.get_type
     *
     * @param get_type the value for mon_car_info.get_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setGet_type(String get_type) {
        this.get_type = get_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.leave_factory_time
     *
     * @return the value of mon_car_info.leave_factory_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getLeave_factory_time() {
        return leave_factory_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.leave_factory_time
     *
     * @param leave_factory_time the value for mon_car_info.leave_factory_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setLeave_factory_time(Date leave_factory_time) {
        this.leave_factory_time = leave_factory_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.certificate_time
     *
     * @return the value of mon_car_info.certificate_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getCertificate_time() {
        return certificate_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.certificate_time
     *
     * @param certificate_time the value for mon_car_info.certificate_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCertificate_time(Date certificate_time) {
        this.certificate_time = certificate_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.yearinspect_time
     *
     * @return the value of mon_car_info.yearinspect_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getYearinspect_time() {
        return yearinspect_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.yearinspect_time
     *
     * @param yearinspect_time the value for mon_car_info.yearinspect_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setYearinspect_time(Date yearinspect_time) {
        this.yearinspect_time = yearinspect_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_img_name
     *
     * @return the value of mon_car_info.car_img_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCar_img_name() {
        return car_img_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_img_name
     *
     * @param car_img_name the value for mon_car_info.car_img_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_img_name(String car_img_name) {
        this.car_img_name = car_img_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.car_img_path
     *
     * @return the value of mon_car_info.car_img_path
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCar_img_path() {
        return car_img_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.car_img_path
     *
     * @param car_img_path the value for mon_car_info.car_img_path
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_img_path(String car_img_path) {
        this.car_img_path = car_img_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.borrow_dept
     *
     * @return the value of mon_car_info.borrow_dept
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getBorrow_dept() {
        return borrow_dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.borrow_dept
     *
     * @param borrow_dept the value for mon_car_info.borrow_dept
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setBorrow_dept(String borrow_dept) {
        this.borrow_dept = borrow_dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.skill_state
     *
     * @return the value of mon_car_info.skill_state
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getSkill_state() {
        return skill_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.skill_state
     *
     * @param skill_state the value for mon_car_info.skill_state
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setSkill_state(Integer skill_state) {
        this.skill_state = skill_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.wifi_num
     *
     * @return the value of mon_car_info.wifi_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getWifi_num() {
        return wifi_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.wifi_num
     *
     * @param wifi_num the value for mon_car_info.wifi_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setWifi_num(String wifi_num) {
        this.wifi_num = wifi_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.syna_flag
     *
     * @return the value of mon_car_info.syna_flag
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getSyna_flag() {
        return syna_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.syna_flag
     *
     * @param syna_flag the value for mon_car_info.syna_flag
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setSyna_flag(String syna_flag) {
        this.syna_flag = syna_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.city_code
     *
     * @return the value of mon_car_info.city_code
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCity_code() {
        return city_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.city_code
     *
     * @param city_code the value for mon_car_info.city_code
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCity_code(String city_code) {
        this.city_code = city_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.old_id
     *
     * @return the value of mon_car_info.old_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Long getOld_id() {
        return old_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.old_id
     *
     * @param old_id the value for mon_car_info.old_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setOld_id(Long old_id) {
        this.old_id = old_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_info.syna_time
     *
     * @return the value of mon_car_info.syna_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getSyna_time() {
        return syna_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_info.syna_time
     *
     * @param syna_time the value for mon_car_info.syna_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setSyna_time(Date syna_time) {
        this.syna_time = syna_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", car_num=").append(car_num);
        sb.append(", car_number=").append(car_number);
        sb.append(", car_type=").append(car_type);
        sb.append(", car_model=").append(car_model);
        sb.append(", car_state=").append(car_state);
        sb.append(", department_id=").append(department_id);
        sb.append(", car_manufacturers=").append(car_manufacturers);
        sb.append(", car_milage=").append(car_milage);
        sb.append(", car_icon=").append(car_icon);
        sb.append(", car_tree_icon=").append(car_tree_icon);
        sb.append(", car_color=").append(car_color);
        sb.append(", car_capacity=").append(car_capacity);
        sb.append(", past_time=").append(past_time);
        sb.append(", add_time=").append(add_time);
        sb.append(", car_price=").append(car_price);
        sb.append(", license_plate_color=").append(license_plate_color);
        sb.append(", car_login=").append(car_login);
        sb.append(", img_name=").append(img_name);
        sb.append(", img_save_name=").append(img_save_name);
        sb.append(", is_flag=").append(is_flag);
        sb.append(", car_remark=").append(car_remark);
        sb.append(", car_employState=").append(car_employState);
        sb.append(", car_seating=").append(car_seating);
        sb.append(", car_xsz=").append(car_xsz);
        sb.append(", car_money=").append(car_money);
        sb.append(", car_vin=").append(car_vin);
        sb.append(", car_pl=").append(car_pl);
        sb.append(", car_zg=").append(car_zg);
        sb.append(", car_zb=").append(car_zb);
        sb.append(", car_ts=").append(car_ts);
        sb.append(", car_chegai=").append(car_chegai);
        sb.append(", car_speed=").append(car_speed);
        sb.append(", car_guige_xinghao=").append(car_guige_xinghao);
        sb.append(", car_xingzhi=").append(car_xingzhi);
        sb.append(", car_zichankahao=").append(car_zichankahao);
        sb.append(", car_youliao_type=").append(car_youliao_type);
        sb.append(", car_cj_number=").append(car_cj_number);
        sb.append(", car_fdj_number=").append(car_fdj_number);
        sb.append(", car_baoyangT=").append(car_baoyangT);
        sb.append(", chedui=").append(chedui);
        sb.append(", serial_number=").append(serial_number);
        sb.append(", drive_mode=").append(drive_mode);
        sb.append(", car_license_time=").append(car_license_time);
        sb.append(", power=").append(power);
        sb.append(", oil_consumption=").append(oil_consumption);
        sb.append(", car_register_number=").append(car_register_number);
        sb.append(", car_register_time=").append(car_register_time);
        sb.append(", car_fdj_model=").append(car_fdj_model);
        sb.append(", additional_tax_number=").append(additional_tax_number);
        sb.append(", scrap_time=").append(scrap_time);
        sb.append(", safety_km=").append(safety_km);
        sb.append(", source_country=").append(source_country);
        sb.append(", fuel_type=").append(fuel_type);
        sb.append(", swerve_type=").append(swerve_type);
        sb.append(", tyre_num=").append(tyre_num);
        sb.append(", tyre_distance=").append(tyre_distance);
        sb.append(", tyre_standard=").append(tyre_standard);
        sb.append(", axle_num=").append(axle_num);
        sb.append(", axle_distance=").append(axle_distance);
        sb.append(", out_size=").append(out_size);
        sb.append(", total_quality=").append(total_quality);
        sb.append(", get_type=").append(get_type);
        sb.append(", leave_factory_time=").append(leave_factory_time);
        sb.append(", certificate_time=").append(certificate_time);
        sb.append(", yearinspect_time=").append(yearinspect_time);
        sb.append(", car_img_name=").append(car_img_name);
        sb.append(", car_img_path=").append(car_img_path);
        sb.append(", borrow_dept=").append(borrow_dept);
        sb.append(", skill_state=").append(skill_state);
        sb.append(", wifi_num=").append(wifi_num);
        sb.append(", syna_flag=").append(syna_flag);
        sb.append(", city_code=").append(city_code);
        sb.append(", old_id=").append(old_id);
        sb.append(", syna_time=").append(syna_time);
        sb.append("]");
        return sb.toString();
    }
}