package com.github.kyrenesjtv.springboot2.springboot2_withsql.po;

public class MonCarTypeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_type_info.id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_type_info.car_type_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String car_type_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_type_info.seatNum
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer seatNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_type_info.picture_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String picture_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_type_info.id
     *
     * @return the value of mon_car_type_info.id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_type_info.id
     *
     * @param id the value for mon_car_type_info.id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_type_info.car_type_name
     *
     * @return the value of mon_car_type_info.car_type_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCar_type_name() {
        return car_type_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_type_info.car_type_name
     *
     * @param car_type_name the value for mon_car_type_info.car_type_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCar_type_name(String car_type_name) {
        this.car_type_name = car_type_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_type_info.seatNum
     *
     * @return the value of mon_car_type_info.seatNum
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getSeatNum() {
        return seatNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_type_info.seatNum
     *
     * @param seatNum the value for mon_car_type_info.seatNum
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setSeatNum(Integer seatNum) {
        this.seatNum = seatNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_type_info.picture_name
     *
     * @return the value of mon_car_type_info.picture_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getPicture_name() {
        return picture_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_type_info.picture_name
     *
     * @param picture_name the value for mon_car_type_info.picture_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setPicture_name(String picture_name) {
        this.picture_name = picture_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_type_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", car_type_name=").append(car_type_name);
        sb.append(", seatNum=").append(seatNum);
        sb.append(", picture_name=").append(picture_name);
        sb.append("]");
        return sb.toString();
    }
}