package com.github.kyrenesjtv.springboot2.springboot2_withsql.po;

import java.math.BigDecimal;
import java.util.Date;

public class MonCarBalanceInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_balance_info.id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_balance_info.daka_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer daka_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_balance_info.balance_state
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer balance_state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_balance_info.balance_payment
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private BigDecimal balance_payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_balance_info.balance_billing_state
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer balance_billing_state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_balance_info.balance_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date balance_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_balance_info.city_code
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String city_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_balance_info.old_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Long old_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_balance_info.syna_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date syna_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_balance_info.id
     *
     * @return the value of mon_car_balance_info.id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_balance_info.id
     *
     * @param id the value for mon_car_balance_info.id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_balance_info.daka_id
     *
     * @return the value of mon_car_balance_info.daka_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getDaka_id() {
        return daka_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_balance_info.daka_id
     *
     * @param daka_id the value for mon_car_balance_info.daka_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDaka_id(Integer daka_id) {
        this.daka_id = daka_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_balance_info.balance_state
     *
     * @return the value of mon_car_balance_info.balance_state
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getBalance_state() {
        return balance_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_balance_info.balance_state
     *
     * @param balance_state the value for mon_car_balance_info.balance_state
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setBalance_state(Integer balance_state) {
        this.balance_state = balance_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_balance_info.balance_payment
     *
     * @return the value of mon_car_balance_info.balance_payment
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public BigDecimal getBalance_payment() {
        return balance_payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_balance_info.balance_payment
     *
     * @param balance_payment the value for mon_car_balance_info.balance_payment
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setBalance_payment(BigDecimal balance_payment) {
        this.balance_payment = balance_payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_balance_info.balance_billing_state
     *
     * @return the value of mon_car_balance_info.balance_billing_state
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getBalance_billing_state() {
        return balance_billing_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_balance_info.balance_billing_state
     *
     * @param balance_billing_state the value for mon_car_balance_info.balance_billing_state
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setBalance_billing_state(Integer balance_billing_state) {
        this.balance_billing_state = balance_billing_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_balance_info.balance_time
     *
     * @return the value of mon_car_balance_info.balance_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getBalance_time() {
        return balance_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_balance_info.balance_time
     *
     * @param balance_time the value for mon_car_balance_info.balance_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setBalance_time(Date balance_time) {
        this.balance_time = balance_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_balance_info.city_code
     *
     * @return the value of mon_car_balance_info.city_code
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCity_code() {
        return city_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_balance_info.city_code
     *
     * @param city_code the value for mon_car_balance_info.city_code
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCity_code(String city_code) {
        this.city_code = city_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_balance_info.old_id
     *
     * @return the value of mon_car_balance_info.old_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Long getOld_id() {
        return old_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_balance_info.old_id
     *
     * @param old_id the value for mon_car_balance_info.old_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setOld_id(Long old_id) {
        this.old_id = old_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_balance_info.syna_time
     *
     * @return the value of mon_car_balance_info.syna_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getSyna_time() {
        return syna_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_balance_info.syna_time
     *
     * @param syna_time the value for mon_car_balance_info.syna_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setSyna_time(Date syna_time) {
        this.syna_time = syna_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_balance_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", daka_id=").append(daka_id);
        sb.append(", balance_state=").append(balance_state);
        sb.append(", balance_payment=").append(balance_payment);
        sb.append(", balance_billing_state=").append(balance_billing_state);
        sb.append(", balance_time=").append(balance_time);
        sb.append(", city_code=").append(city_code);
        sb.append(", old_id=").append(old_id);
        sb.append(", syna_time=").append(syna_time);
        sb.append("]");
        return sb.toString();
    }
}