package com.github.kyrenesjtv.springboot2.springboot2_withsql.po;

import java.util.Date;

public class MonCarApplyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_name_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer apply_name_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_car_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer apply_car_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_driver_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer apply_driver_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_name_phone
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String apply_name_phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_man_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer apply_man_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date apply_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer apply_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_state
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer apply_state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_flow_state
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer apply_flow_state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_dept_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer apply_dept_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_user_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer apply_user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_use_range
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String apply_use_range;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_use_address
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String apply_use_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_destination
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String apply_destination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_use_phone
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String apply_use_phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_use_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date apply_use_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_back_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date apply_back_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_out_km
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double apply_out_km;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_back_km
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double apply_back_km;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_income
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Long apply_income;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_gl_subsidy
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Long apply_gl_subsidy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_cl_subsidy
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Long apply_cl_subsidy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_jb_subsidy
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Long apply_jb_subsidy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_toll
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Long apply_toll;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_car_wash
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Long apply_car_wash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_car_park
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Long apply_car_park;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_car_water
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Long apply_car_water;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_other_money
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Long apply_other_money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_start_lm
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String apply_start_lm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_end_lm
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String apply_end_lm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_remark
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String apply_remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_ed_zaizhong
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String apply_ed_zaizhong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_qy_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer apply_qy_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_sx_pople
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String apply_sx_pople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_check_user_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer apply_check_user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_check_yj
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String apply_check_yj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_check_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date apply_check_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_bz
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String apply_bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.yong_che_ren
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String yong_che_ren;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.yong_che_zhiwei
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String yong_che_zhiwei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.yong_che_no
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String yong_che_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.yong_che_xz
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String yong_che_xz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.gps_km
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double gps_km;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.xs_km
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double xs_km;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.return_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date return_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.driverDDZT
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer driverDDZT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.currCheckPopleTime
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date currCheckPopleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.dispatchTime
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date dispatchTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.currCheckPopleId
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer currCheckPopleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.dispatchId
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer dispatchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.backId
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer backId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_shenqingCar_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer apply_shenqingCar_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_use_day
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer apply_use_day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_car_food
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double apply_car_food;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.quxiao_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date quxiao_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.start_longitude
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String start_longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.start_latitude
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String start_latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.end_longitude
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String end_longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.end_latitude
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String end_latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_fwzx_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer apply_fwzx_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_convoy_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer apply_convoy_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.day_price
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double day_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.halfDay_price
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double halfDay_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.km_price
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Double km_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.is_look
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer is_look;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_ydyc_flag
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer apply_ydyc_flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.ydyc_check_flag
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer ydyc_check_flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.is_send
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer is_send;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.ramarkto
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String ramarkto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.apply_stay
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Long apply_stay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.rejoin_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date rejoin_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.audit_pass_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date audit_pass_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.audit_reject_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date audit_reject_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.patcher_pass_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date patcher_pass_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.patcher_reject_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date patcher_reject_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.patcher_car_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date patcher_car_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.cancel_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date cancel_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.free_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer free_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.printType
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer printType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.trip_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer trip_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.old_apply_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer old_apply_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.city_code
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String city_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.trip_content
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String trip_content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_car_apply_info.syna_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date syna_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.id
     *
     * @return the value of mon_car_apply_info.id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.id
     *
     * @param id the value for mon_car_apply_info.id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_name_id
     *
     * @return the value of mon_car_apply_info.apply_name_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getApply_name_id() {
        return apply_name_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_name_id
     *
     * @param apply_name_id the value for mon_car_apply_info.apply_name_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_name_id(Integer apply_name_id) {
        this.apply_name_id = apply_name_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_car_id
     *
     * @return the value of mon_car_apply_info.apply_car_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getApply_car_id() {
        return apply_car_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_car_id
     *
     * @param apply_car_id the value for mon_car_apply_info.apply_car_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_car_id(Integer apply_car_id) {
        this.apply_car_id = apply_car_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_driver_id
     *
     * @return the value of mon_car_apply_info.apply_driver_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getApply_driver_id() {
        return apply_driver_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_driver_id
     *
     * @param apply_driver_id the value for mon_car_apply_info.apply_driver_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_driver_id(Integer apply_driver_id) {
        this.apply_driver_id = apply_driver_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_name_phone
     *
     * @return the value of mon_car_apply_info.apply_name_phone
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getApply_name_phone() {
        return apply_name_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_name_phone
     *
     * @param apply_name_phone the value for mon_car_apply_info.apply_name_phone
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_name_phone(String apply_name_phone) {
        this.apply_name_phone = apply_name_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_man_num
     *
     * @return the value of mon_car_apply_info.apply_man_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getApply_man_num() {
        return apply_man_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_man_num
     *
     * @param apply_man_num the value for mon_car_apply_info.apply_man_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_man_num(Integer apply_man_num) {
        this.apply_man_num = apply_man_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_time
     *
     * @return the value of mon_car_apply_info.apply_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getApply_time() {
        return apply_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_time
     *
     * @param apply_time the value for mon_car_apply_info.apply_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_time(Date apply_time) {
        this.apply_time = apply_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_type
     *
     * @return the value of mon_car_apply_info.apply_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getApply_type() {
        return apply_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_type
     *
     * @param apply_type the value for mon_car_apply_info.apply_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_type(Integer apply_type) {
        this.apply_type = apply_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_state
     *
     * @return the value of mon_car_apply_info.apply_state
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getApply_state() {
        return apply_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_state
     *
     * @param apply_state the value for mon_car_apply_info.apply_state
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_state(Integer apply_state) {
        this.apply_state = apply_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_flow_state
     *
     * @return the value of mon_car_apply_info.apply_flow_state
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getApply_flow_state() {
        return apply_flow_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_flow_state
     *
     * @param apply_flow_state the value for mon_car_apply_info.apply_flow_state
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_flow_state(Integer apply_flow_state) {
        this.apply_flow_state = apply_flow_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_dept_id
     *
     * @return the value of mon_car_apply_info.apply_dept_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getApply_dept_id() {
        return apply_dept_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_dept_id
     *
     * @param apply_dept_id the value for mon_car_apply_info.apply_dept_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_dept_id(Integer apply_dept_id) {
        this.apply_dept_id = apply_dept_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_user_id
     *
     * @return the value of mon_car_apply_info.apply_user_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getApply_user_id() {
        return apply_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_user_id
     *
     * @param apply_user_id the value for mon_car_apply_info.apply_user_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_user_id(Integer apply_user_id) {
        this.apply_user_id = apply_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_use_range
     *
     * @return the value of mon_car_apply_info.apply_use_range
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getApply_use_range() {
        return apply_use_range;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_use_range
     *
     * @param apply_use_range the value for mon_car_apply_info.apply_use_range
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_use_range(String apply_use_range) {
        this.apply_use_range = apply_use_range;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_use_address
     *
     * @return the value of mon_car_apply_info.apply_use_address
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getApply_use_address() {
        return apply_use_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_use_address
     *
     * @param apply_use_address the value for mon_car_apply_info.apply_use_address
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_use_address(String apply_use_address) {
        this.apply_use_address = apply_use_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_destination
     *
     * @return the value of mon_car_apply_info.apply_destination
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getApply_destination() {
        return apply_destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_destination
     *
     * @param apply_destination the value for mon_car_apply_info.apply_destination
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_destination(String apply_destination) {
        this.apply_destination = apply_destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_use_phone
     *
     * @return the value of mon_car_apply_info.apply_use_phone
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getApply_use_phone() {
        return apply_use_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_use_phone
     *
     * @param apply_use_phone the value for mon_car_apply_info.apply_use_phone
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_use_phone(String apply_use_phone) {
        this.apply_use_phone = apply_use_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_use_time
     *
     * @return the value of mon_car_apply_info.apply_use_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getApply_use_time() {
        return apply_use_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_use_time
     *
     * @param apply_use_time the value for mon_car_apply_info.apply_use_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_use_time(Date apply_use_time) {
        this.apply_use_time = apply_use_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_back_time
     *
     * @return the value of mon_car_apply_info.apply_back_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getApply_back_time() {
        return apply_back_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_back_time
     *
     * @param apply_back_time the value for mon_car_apply_info.apply_back_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_back_time(Date apply_back_time) {
        this.apply_back_time = apply_back_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_out_km
     *
     * @return the value of mon_car_apply_info.apply_out_km
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getApply_out_km() {
        return apply_out_km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_out_km
     *
     * @param apply_out_km the value for mon_car_apply_info.apply_out_km
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_out_km(Double apply_out_km) {
        this.apply_out_km = apply_out_km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_back_km
     *
     * @return the value of mon_car_apply_info.apply_back_km
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getApply_back_km() {
        return apply_back_km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_back_km
     *
     * @param apply_back_km the value for mon_car_apply_info.apply_back_km
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_back_km(Double apply_back_km) {
        this.apply_back_km = apply_back_km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_income
     *
     * @return the value of mon_car_apply_info.apply_income
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Long getApply_income() {
        return apply_income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_income
     *
     * @param apply_income the value for mon_car_apply_info.apply_income
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_income(Long apply_income) {
        this.apply_income = apply_income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_gl_subsidy
     *
     * @return the value of mon_car_apply_info.apply_gl_subsidy
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Long getApply_gl_subsidy() {
        return apply_gl_subsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_gl_subsidy
     *
     * @param apply_gl_subsidy the value for mon_car_apply_info.apply_gl_subsidy
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_gl_subsidy(Long apply_gl_subsidy) {
        this.apply_gl_subsidy = apply_gl_subsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_cl_subsidy
     *
     * @return the value of mon_car_apply_info.apply_cl_subsidy
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Long getApply_cl_subsidy() {
        return apply_cl_subsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_cl_subsidy
     *
     * @param apply_cl_subsidy the value for mon_car_apply_info.apply_cl_subsidy
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_cl_subsidy(Long apply_cl_subsidy) {
        this.apply_cl_subsidy = apply_cl_subsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_jb_subsidy
     *
     * @return the value of mon_car_apply_info.apply_jb_subsidy
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Long getApply_jb_subsidy() {
        return apply_jb_subsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_jb_subsidy
     *
     * @param apply_jb_subsidy the value for mon_car_apply_info.apply_jb_subsidy
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_jb_subsidy(Long apply_jb_subsidy) {
        this.apply_jb_subsidy = apply_jb_subsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_toll
     *
     * @return the value of mon_car_apply_info.apply_toll
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Long getApply_toll() {
        return apply_toll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_toll
     *
     * @param apply_toll the value for mon_car_apply_info.apply_toll
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_toll(Long apply_toll) {
        this.apply_toll = apply_toll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_car_wash
     *
     * @return the value of mon_car_apply_info.apply_car_wash
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Long getApply_car_wash() {
        return apply_car_wash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_car_wash
     *
     * @param apply_car_wash the value for mon_car_apply_info.apply_car_wash
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_car_wash(Long apply_car_wash) {
        this.apply_car_wash = apply_car_wash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_car_park
     *
     * @return the value of mon_car_apply_info.apply_car_park
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Long getApply_car_park() {
        return apply_car_park;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_car_park
     *
     * @param apply_car_park the value for mon_car_apply_info.apply_car_park
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_car_park(Long apply_car_park) {
        this.apply_car_park = apply_car_park;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_car_water
     *
     * @return the value of mon_car_apply_info.apply_car_water
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Long getApply_car_water() {
        return apply_car_water;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_car_water
     *
     * @param apply_car_water the value for mon_car_apply_info.apply_car_water
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_car_water(Long apply_car_water) {
        this.apply_car_water = apply_car_water;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_other_money
     *
     * @return the value of mon_car_apply_info.apply_other_money
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Long getApply_other_money() {
        return apply_other_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_other_money
     *
     * @param apply_other_money the value for mon_car_apply_info.apply_other_money
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_other_money(Long apply_other_money) {
        this.apply_other_money = apply_other_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_start_lm
     *
     * @return the value of mon_car_apply_info.apply_start_lm
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getApply_start_lm() {
        return apply_start_lm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_start_lm
     *
     * @param apply_start_lm the value for mon_car_apply_info.apply_start_lm
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_start_lm(String apply_start_lm) {
        this.apply_start_lm = apply_start_lm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_end_lm
     *
     * @return the value of mon_car_apply_info.apply_end_lm
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getApply_end_lm() {
        return apply_end_lm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_end_lm
     *
     * @param apply_end_lm the value for mon_car_apply_info.apply_end_lm
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_end_lm(String apply_end_lm) {
        this.apply_end_lm = apply_end_lm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_remark
     *
     * @return the value of mon_car_apply_info.apply_remark
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getApply_remark() {
        return apply_remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_remark
     *
     * @param apply_remark the value for mon_car_apply_info.apply_remark
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_remark(String apply_remark) {
        this.apply_remark = apply_remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_ed_zaizhong
     *
     * @return the value of mon_car_apply_info.apply_ed_zaizhong
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getApply_ed_zaizhong() {
        return apply_ed_zaizhong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_ed_zaizhong
     *
     * @param apply_ed_zaizhong the value for mon_car_apply_info.apply_ed_zaizhong
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_ed_zaizhong(String apply_ed_zaizhong) {
        this.apply_ed_zaizhong = apply_ed_zaizhong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_qy_id
     *
     * @return the value of mon_car_apply_info.apply_qy_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getApply_qy_id() {
        return apply_qy_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_qy_id
     *
     * @param apply_qy_id the value for mon_car_apply_info.apply_qy_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_qy_id(Integer apply_qy_id) {
        this.apply_qy_id = apply_qy_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_sx_pople
     *
     * @return the value of mon_car_apply_info.apply_sx_pople
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getApply_sx_pople() {
        return apply_sx_pople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_sx_pople
     *
     * @param apply_sx_pople the value for mon_car_apply_info.apply_sx_pople
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_sx_pople(String apply_sx_pople) {
        this.apply_sx_pople = apply_sx_pople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_check_user_id
     *
     * @return the value of mon_car_apply_info.apply_check_user_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getApply_check_user_id() {
        return apply_check_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_check_user_id
     *
     * @param apply_check_user_id the value for mon_car_apply_info.apply_check_user_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_check_user_id(Integer apply_check_user_id) {
        this.apply_check_user_id = apply_check_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_check_yj
     *
     * @return the value of mon_car_apply_info.apply_check_yj
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getApply_check_yj() {
        return apply_check_yj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_check_yj
     *
     * @param apply_check_yj the value for mon_car_apply_info.apply_check_yj
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_check_yj(String apply_check_yj) {
        this.apply_check_yj = apply_check_yj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_check_time
     *
     * @return the value of mon_car_apply_info.apply_check_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getApply_check_time() {
        return apply_check_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_check_time
     *
     * @param apply_check_time the value for mon_car_apply_info.apply_check_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_check_time(Date apply_check_time) {
        this.apply_check_time = apply_check_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_bz
     *
     * @return the value of mon_car_apply_info.apply_bz
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getApply_bz() {
        return apply_bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_bz
     *
     * @param apply_bz the value for mon_car_apply_info.apply_bz
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_bz(String apply_bz) {
        this.apply_bz = apply_bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.yong_che_ren
     *
     * @return the value of mon_car_apply_info.yong_che_ren
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getYong_che_ren() {
        return yong_che_ren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.yong_che_ren
     *
     * @param yong_che_ren the value for mon_car_apply_info.yong_che_ren
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setYong_che_ren(String yong_che_ren) {
        this.yong_che_ren = yong_che_ren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.yong_che_zhiwei
     *
     * @return the value of mon_car_apply_info.yong_che_zhiwei
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getYong_che_zhiwei() {
        return yong_che_zhiwei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.yong_che_zhiwei
     *
     * @param yong_che_zhiwei the value for mon_car_apply_info.yong_che_zhiwei
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setYong_che_zhiwei(String yong_che_zhiwei) {
        this.yong_che_zhiwei = yong_che_zhiwei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.yong_che_no
     *
     * @return the value of mon_car_apply_info.yong_che_no
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getYong_che_no() {
        return yong_che_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.yong_che_no
     *
     * @param yong_che_no the value for mon_car_apply_info.yong_che_no
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setYong_che_no(String yong_che_no) {
        this.yong_che_no = yong_che_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.yong_che_xz
     *
     * @return the value of mon_car_apply_info.yong_che_xz
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getYong_che_xz() {
        return yong_che_xz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.yong_che_xz
     *
     * @param yong_che_xz the value for mon_car_apply_info.yong_che_xz
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setYong_che_xz(String yong_che_xz) {
        this.yong_che_xz = yong_che_xz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.gps_km
     *
     * @return the value of mon_car_apply_info.gps_km
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getGps_km() {
        return gps_km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.gps_km
     *
     * @param gps_km the value for mon_car_apply_info.gps_km
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setGps_km(Double gps_km) {
        this.gps_km = gps_km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.xs_km
     *
     * @return the value of mon_car_apply_info.xs_km
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getXs_km() {
        return xs_km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.xs_km
     *
     * @param xs_km the value for mon_car_apply_info.xs_km
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setXs_km(Double xs_km) {
        this.xs_km = xs_km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.return_time
     *
     * @return the value of mon_car_apply_info.return_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getReturn_time() {
        return return_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.return_time
     *
     * @param return_time the value for mon_car_apply_info.return_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setReturn_time(Date return_time) {
        this.return_time = return_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.driverDDZT
     *
     * @return the value of mon_car_apply_info.driverDDZT
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getDriverDDZT() {
        return driverDDZT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.driverDDZT
     *
     * @param driverDDZT the value for mon_car_apply_info.driverDDZT
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDriverDDZT(Integer driverDDZT) {
        this.driverDDZT = driverDDZT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.currCheckPopleTime
     *
     * @return the value of mon_car_apply_info.currCheckPopleTime
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getCurrCheckPopleTime() {
        return currCheckPopleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.currCheckPopleTime
     *
     * @param currCheckPopleTime the value for mon_car_apply_info.currCheckPopleTime
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCurrCheckPopleTime(Date currCheckPopleTime) {
        this.currCheckPopleTime = currCheckPopleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.dispatchTime
     *
     * @return the value of mon_car_apply_info.dispatchTime
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getDispatchTime() {
        return dispatchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.dispatchTime
     *
     * @param dispatchTime the value for mon_car_apply_info.dispatchTime
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDispatchTime(Date dispatchTime) {
        this.dispatchTime = dispatchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.currCheckPopleId
     *
     * @return the value of mon_car_apply_info.currCheckPopleId
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getCurrCheckPopleId() {
        return currCheckPopleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.currCheckPopleId
     *
     * @param currCheckPopleId the value for mon_car_apply_info.currCheckPopleId
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCurrCheckPopleId(Integer currCheckPopleId) {
        this.currCheckPopleId = currCheckPopleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.dispatchId
     *
     * @return the value of mon_car_apply_info.dispatchId
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getDispatchId() {
        return dispatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.dispatchId
     *
     * @param dispatchId the value for mon_car_apply_info.dispatchId
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDispatchId(Integer dispatchId) {
        this.dispatchId = dispatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.backId
     *
     * @return the value of mon_car_apply_info.backId
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getBackId() {
        return backId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.backId
     *
     * @param backId the value for mon_car_apply_info.backId
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setBackId(Integer backId) {
        this.backId = backId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_shenqingCar_type
     *
     * @return the value of mon_car_apply_info.apply_shenqingCar_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getApply_shenqingCar_type() {
        return apply_shenqingCar_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_shenqingCar_type
     *
     * @param apply_shenqingCar_type the value for mon_car_apply_info.apply_shenqingCar_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_shenqingCar_type(Integer apply_shenqingCar_type) {
        this.apply_shenqingCar_type = apply_shenqingCar_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_use_day
     *
     * @return the value of mon_car_apply_info.apply_use_day
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getApply_use_day() {
        return apply_use_day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_use_day
     *
     * @param apply_use_day the value for mon_car_apply_info.apply_use_day
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_use_day(Integer apply_use_day) {
        this.apply_use_day = apply_use_day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_car_food
     *
     * @return the value of mon_car_apply_info.apply_car_food
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getApply_car_food() {
        return apply_car_food;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_car_food
     *
     * @param apply_car_food the value for mon_car_apply_info.apply_car_food
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_car_food(Double apply_car_food) {
        this.apply_car_food = apply_car_food;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.quxiao_time
     *
     * @return the value of mon_car_apply_info.quxiao_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getQuxiao_time() {
        return quxiao_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.quxiao_time
     *
     * @param quxiao_time the value for mon_car_apply_info.quxiao_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setQuxiao_time(Date quxiao_time) {
        this.quxiao_time = quxiao_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.start_longitude
     *
     * @return the value of mon_car_apply_info.start_longitude
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getStart_longitude() {
        return start_longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.start_longitude
     *
     * @param start_longitude the value for mon_car_apply_info.start_longitude
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setStart_longitude(String start_longitude) {
        this.start_longitude = start_longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.start_latitude
     *
     * @return the value of mon_car_apply_info.start_latitude
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getStart_latitude() {
        return start_latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.start_latitude
     *
     * @param start_latitude the value for mon_car_apply_info.start_latitude
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setStart_latitude(String start_latitude) {
        this.start_latitude = start_latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.end_longitude
     *
     * @return the value of mon_car_apply_info.end_longitude
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getEnd_longitude() {
        return end_longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.end_longitude
     *
     * @param end_longitude the value for mon_car_apply_info.end_longitude
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setEnd_longitude(String end_longitude) {
        this.end_longitude = end_longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.end_latitude
     *
     * @return the value of mon_car_apply_info.end_latitude
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getEnd_latitude() {
        return end_latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.end_latitude
     *
     * @param end_latitude the value for mon_car_apply_info.end_latitude
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setEnd_latitude(String end_latitude) {
        this.end_latitude = end_latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_fwzx_id
     *
     * @return the value of mon_car_apply_info.apply_fwzx_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getApply_fwzx_id() {
        return apply_fwzx_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_fwzx_id
     *
     * @param apply_fwzx_id the value for mon_car_apply_info.apply_fwzx_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_fwzx_id(Integer apply_fwzx_id) {
        this.apply_fwzx_id = apply_fwzx_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_convoy_id
     *
     * @return the value of mon_car_apply_info.apply_convoy_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getApply_convoy_id() {
        return apply_convoy_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_convoy_id
     *
     * @param apply_convoy_id the value for mon_car_apply_info.apply_convoy_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_convoy_id(Integer apply_convoy_id) {
        this.apply_convoy_id = apply_convoy_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.day_price
     *
     * @return the value of mon_car_apply_info.day_price
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getDay_price() {
        return day_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.day_price
     *
     * @param day_price the value for mon_car_apply_info.day_price
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDay_price(Double day_price) {
        this.day_price = day_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.halfDay_price
     *
     * @return the value of mon_car_apply_info.halfDay_price
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getHalfDay_price() {
        return halfDay_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.halfDay_price
     *
     * @param halfDay_price the value for mon_car_apply_info.halfDay_price
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setHalfDay_price(Double halfDay_price) {
        this.halfDay_price = halfDay_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.km_price
     *
     * @return the value of mon_car_apply_info.km_price
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Double getKm_price() {
        return km_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.km_price
     *
     * @param km_price the value for mon_car_apply_info.km_price
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setKm_price(Double km_price) {
        this.km_price = km_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.is_look
     *
     * @return the value of mon_car_apply_info.is_look
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getIs_look() {
        return is_look;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.is_look
     *
     * @param is_look the value for mon_car_apply_info.is_look
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setIs_look(Integer is_look) {
        this.is_look = is_look;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_ydyc_flag
     *
     * @return the value of mon_car_apply_info.apply_ydyc_flag
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getApply_ydyc_flag() {
        return apply_ydyc_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_ydyc_flag
     *
     * @param apply_ydyc_flag the value for mon_car_apply_info.apply_ydyc_flag
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_ydyc_flag(Integer apply_ydyc_flag) {
        this.apply_ydyc_flag = apply_ydyc_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.ydyc_check_flag
     *
     * @return the value of mon_car_apply_info.ydyc_check_flag
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getYdyc_check_flag() {
        return ydyc_check_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.ydyc_check_flag
     *
     * @param ydyc_check_flag the value for mon_car_apply_info.ydyc_check_flag
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setYdyc_check_flag(Integer ydyc_check_flag) {
        this.ydyc_check_flag = ydyc_check_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.is_send
     *
     * @return the value of mon_car_apply_info.is_send
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getIs_send() {
        return is_send;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.is_send
     *
     * @param is_send the value for mon_car_apply_info.is_send
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setIs_send(Integer is_send) {
        this.is_send = is_send;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.ramarkto
     *
     * @return the value of mon_car_apply_info.ramarkto
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getRamarkto() {
        return ramarkto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.ramarkto
     *
     * @param ramarkto the value for mon_car_apply_info.ramarkto
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setRamarkto(String ramarkto) {
        this.ramarkto = ramarkto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.apply_stay
     *
     * @return the value of mon_car_apply_info.apply_stay
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Long getApply_stay() {
        return apply_stay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.apply_stay
     *
     * @param apply_stay the value for mon_car_apply_info.apply_stay
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setApply_stay(Long apply_stay) {
        this.apply_stay = apply_stay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.rejoin_time
     *
     * @return the value of mon_car_apply_info.rejoin_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getRejoin_time() {
        return rejoin_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.rejoin_time
     *
     * @param rejoin_time the value for mon_car_apply_info.rejoin_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setRejoin_time(Date rejoin_time) {
        this.rejoin_time = rejoin_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.audit_pass_time
     *
     * @return the value of mon_car_apply_info.audit_pass_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getAudit_pass_time() {
        return audit_pass_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.audit_pass_time
     *
     * @param audit_pass_time the value for mon_car_apply_info.audit_pass_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setAudit_pass_time(Date audit_pass_time) {
        this.audit_pass_time = audit_pass_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.audit_reject_time
     *
     * @return the value of mon_car_apply_info.audit_reject_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getAudit_reject_time() {
        return audit_reject_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.audit_reject_time
     *
     * @param audit_reject_time the value for mon_car_apply_info.audit_reject_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setAudit_reject_time(Date audit_reject_time) {
        this.audit_reject_time = audit_reject_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.patcher_pass_time
     *
     * @return the value of mon_car_apply_info.patcher_pass_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getPatcher_pass_time() {
        return patcher_pass_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.patcher_pass_time
     *
     * @param patcher_pass_time the value for mon_car_apply_info.patcher_pass_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setPatcher_pass_time(Date patcher_pass_time) {
        this.patcher_pass_time = patcher_pass_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.patcher_reject_time
     *
     * @return the value of mon_car_apply_info.patcher_reject_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getPatcher_reject_time() {
        return patcher_reject_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.patcher_reject_time
     *
     * @param patcher_reject_time the value for mon_car_apply_info.patcher_reject_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setPatcher_reject_time(Date patcher_reject_time) {
        this.patcher_reject_time = patcher_reject_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.patcher_car_time
     *
     * @return the value of mon_car_apply_info.patcher_car_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getPatcher_car_time() {
        return patcher_car_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.patcher_car_time
     *
     * @param patcher_car_time the value for mon_car_apply_info.patcher_car_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setPatcher_car_time(Date patcher_car_time) {
        this.patcher_car_time = patcher_car_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.cancel_time
     *
     * @return the value of mon_car_apply_info.cancel_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getCancel_time() {
        return cancel_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.cancel_time
     *
     * @param cancel_time the value for mon_car_apply_info.cancel_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCancel_time(Date cancel_time) {
        this.cancel_time = cancel_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.free_type
     *
     * @return the value of mon_car_apply_info.free_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getFree_type() {
        return free_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.free_type
     *
     * @param free_type the value for mon_car_apply_info.free_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setFree_type(Integer free_type) {
        this.free_type = free_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.printType
     *
     * @return the value of mon_car_apply_info.printType
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getPrintType() {
        return printType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.printType
     *
     * @param printType the value for mon_car_apply_info.printType
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setPrintType(Integer printType) {
        this.printType = printType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.trip_type
     *
     * @return the value of mon_car_apply_info.trip_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getTrip_type() {
        return trip_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.trip_type
     *
     * @param trip_type the value for mon_car_apply_info.trip_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setTrip_type(Integer trip_type) {
        this.trip_type = trip_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.old_apply_id
     *
     * @return the value of mon_car_apply_info.old_apply_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getOld_apply_id() {
        return old_apply_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.old_apply_id
     *
     * @param old_apply_id the value for mon_car_apply_info.old_apply_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setOld_apply_id(Integer old_apply_id) {
        this.old_apply_id = old_apply_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.city_code
     *
     * @return the value of mon_car_apply_info.city_code
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCity_code() {
        return city_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.city_code
     *
     * @param city_code the value for mon_car_apply_info.city_code
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCity_code(String city_code) {
        this.city_code = city_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.trip_content
     *
     * @return the value of mon_car_apply_info.trip_content
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getTrip_content() {
        return trip_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.trip_content
     *
     * @param trip_content the value for mon_car_apply_info.trip_content
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setTrip_content(String trip_content) {
        this.trip_content = trip_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_car_apply_info.syna_time
     *
     * @return the value of mon_car_apply_info.syna_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getSyna_time() {
        return syna_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_car_apply_info.syna_time
     *
     * @param syna_time the value for mon_car_apply_info.syna_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setSyna_time(Date syna_time) {
        this.syna_time = syna_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_car_apply_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", apply_name_id=").append(apply_name_id);
        sb.append(", apply_car_id=").append(apply_car_id);
        sb.append(", apply_driver_id=").append(apply_driver_id);
        sb.append(", apply_name_phone=").append(apply_name_phone);
        sb.append(", apply_man_num=").append(apply_man_num);
        sb.append(", apply_time=").append(apply_time);
        sb.append(", apply_type=").append(apply_type);
        sb.append(", apply_state=").append(apply_state);
        sb.append(", apply_flow_state=").append(apply_flow_state);
        sb.append(", apply_dept_id=").append(apply_dept_id);
        sb.append(", apply_user_id=").append(apply_user_id);
        sb.append(", apply_use_range=").append(apply_use_range);
        sb.append(", apply_use_address=").append(apply_use_address);
        sb.append(", apply_destination=").append(apply_destination);
        sb.append(", apply_use_phone=").append(apply_use_phone);
        sb.append(", apply_use_time=").append(apply_use_time);
        sb.append(", apply_back_time=").append(apply_back_time);
        sb.append(", apply_out_km=").append(apply_out_km);
        sb.append(", apply_back_km=").append(apply_back_km);
        sb.append(", apply_income=").append(apply_income);
        sb.append(", apply_gl_subsidy=").append(apply_gl_subsidy);
        sb.append(", apply_cl_subsidy=").append(apply_cl_subsidy);
        sb.append(", apply_jb_subsidy=").append(apply_jb_subsidy);
        sb.append(", apply_toll=").append(apply_toll);
        sb.append(", apply_car_wash=").append(apply_car_wash);
        sb.append(", apply_car_park=").append(apply_car_park);
        sb.append(", apply_car_water=").append(apply_car_water);
        sb.append(", apply_other_money=").append(apply_other_money);
        sb.append(", apply_start_lm=").append(apply_start_lm);
        sb.append(", apply_end_lm=").append(apply_end_lm);
        sb.append(", apply_remark=").append(apply_remark);
        sb.append(", apply_ed_zaizhong=").append(apply_ed_zaizhong);
        sb.append(", apply_qy_id=").append(apply_qy_id);
        sb.append(", apply_sx_pople=").append(apply_sx_pople);
        sb.append(", apply_check_user_id=").append(apply_check_user_id);
        sb.append(", apply_check_yj=").append(apply_check_yj);
        sb.append(", apply_check_time=").append(apply_check_time);
        sb.append(", apply_bz=").append(apply_bz);
        sb.append(", yong_che_ren=").append(yong_che_ren);
        sb.append(", yong_che_zhiwei=").append(yong_che_zhiwei);
        sb.append(", yong_che_no=").append(yong_che_no);
        sb.append(", yong_che_xz=").append(yong_che_xz);
        sb.append(", gps_km=").append(gps_km);
        sb.append(", xs_km=").append(xs_km);
        sb.append(", return_time=").append(return_time);
        sb.append(", driverDDZT=").append(driverDDZT);
        sb.append(", currCheckPopleTime=").append(currCheckPopleTime);
        sb.append(", dispatchTime=").append(dispatchTime);
        sb.append(", currCheckPopleId=").append(currCheckPopleId);
        sb.append(", dispatchId=").append(dispatchId);
        sb.append(", backId=").append(backId);
        sb.append(", apply_shenqingCar_type=").append(apply_shenqingCar_type);
        sb.append(", apply_use_day=").append(apply_use_day);
        sb.append(", apply_car_food=").append(apply_car_food);
        sb.append(", quxiao_time=").append(quxiao_time);
        sb.append(", start_longitude=").append(start_longitude);
        sb.append(", start_latitude=").append(start_latitude);
        sb.append(", end_longitude=").append(end_longitude);
        sb.append(", end_latitude=").append(end_latitude);
        sb.append(", apply_fwzx_id=").append(apply_fwzx_id);
        sb.append(", apply_convoy_id=").append(apply_convoy_id);
        sb.append(", day_price=").append(day_price);
        sb.append(", halfDay_price=").append(halfDay_price);
        sb.append(", km_price=").append(km_price);
        sb.append(", is_look=").append(is_look);
        sb.append(", apply_ydyc_flag=").append(apply_ydyc_flag);
        sb.append(", ydyc_check_flag=").append(ydyc_check_flag);
        sb.append(", is_send=").append(is_send);
        sb.append(", ramarkto=").append(ramarkto);
        sb.append(", apply_stay=").append(apply_stay);
        sb.append(", rejoin_time=").append(rejoin_time);
        sb.append(", audit_pass_time=").append(audit_pass_time);
        sb.append(", audit_reject_time=").append(audit_reject_time);
        sb.append(", patcher_pass_time=").append(patcher_pass_time);
        sb.append(", patcher_reject_time=").append(patcher_reject_time);
        sb.append(", patcher_car_time=").append(patcher_car_time);
        sb.append(", cancel_time=").append(cancel_time);
        sb.append(", free_type=").append(free_type);
        sb.append(", printType=").append(printType);
        sb.append(", trip_type=").append(trip_type);
        sb.append(", old_apply_id=").append(old_apply_id);
        sb.append(", city_code=").append(city_code);
        sb.append(", trip_content=").append(trip_content);
        sb.append(", syna_time=").append(syna_time);
        sb.append("]");
        return sb.toString();
    }
}