package com.github.kyrenesjtv.springboot2.springboot2_withsql.po;

import java.util.Date;

public class MonDepartmentInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.id
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.dept_name
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private String dept_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.dept_type
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private Integer dept_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.dept_super_id
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private Integer dept_super_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.dept_desc
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private String dept_desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.dept_lat
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private String dept_lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.dept_lon
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private String dept_lon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.dept_adress
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private String dept_adress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.is_flag
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private Integer is_flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.dapt_remark
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private String dapt_remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.gs_id
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private Integer gs_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.pt_id
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private Integer pt_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.fw_type
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private Integer fw_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.dept_super_ids
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private String dept_super_ids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.name
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.color
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.qy_id
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private Integer qy_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.orgcoding
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private String orgcoding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.orgallname
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private String orgallname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.dept_flag
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private Integer dept_flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.dept_number
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private String dept_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.syna_time
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private Date syna_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.syna_flag
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private String syna_flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_department_info.geo
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    private String geo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.id
     *
     * @return the value of mon_department_info.id
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.id
     *
     * @param id the value for mon_department_info.id
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.dept_name
     *
     * @return the value of mon_department_info.dept_name
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public String getDept_name() {
        return dept_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.dept_name
     *
     * @param dept_name the value for mon_department_info.dept_name
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setDept_name(String dept_name) {
        this.dept_name = dept_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.dept_type
     *
     * @return the value of mon_department_info.dept_type
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public Integer getDept_type() {
        return dept_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.dept_type
     *
     * @param dept_type the value for mon_department_info.dept_type
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setDept_type(Integer dept_type) {
        this.dept_type = dept_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.dept_super_id
     *
     * @return the value of mon_department_info.dept_super_id
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public Integer getDept_super_id() {
        return dept_super_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.dept_super_id
     *
     * @param dept_super_id the value for mon_department_info.dept_super_id
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setDept_super_id(Integer dept_super_id) {
        this.dept_super_id = dept_super_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.dept_desc
     *
     * @return the value of mon_department_info.dept_desc
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public String getDept_desc() {
        return dept_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.dept_desc
     *
     * @param dept_desc the value for mon_department_info.dept_desc
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setDept_desc(String dept_desc) {
        this.dept_desc = dept_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.dept_lat
     *
     * @return the value of mon_department_info.dept_lat
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public String getDept_lat() {
        return dept_lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.dept_lat
     *
     * @param dept_lat the value for mon_department_info.dept_lat
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setDept_lat(String dept_lat) {
        this.dept_lat = dept_lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.dept_lon
     *
     * @return the value of mon_department_info.dept_lon
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public String getDept_lon() {
        return dept_lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.dept_lon
     *
     * @param dept_lon the value for mon_department_info.dept_lon
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setDept_lon(String dept_lon) {
        this.dept_lon = dept_lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.dept_adress
     *
     * @return the value of mon_department_info.dept_adress
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public String getDept_adress() {
        return dept_adress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.dept_adress
     *
     * @param dept_adress the value for mon_department_info.dept_adress
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setDept_adress(String dept_adress) {
        this.dept_adress = dept_adress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.is_flag
     *
     * @return the value of mon_department_info.is_flag
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public Integer getIs_flag() {
        return is_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.is_flag
     *
     * @param is_flag the value for mon_department_info.is_flag
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setIs_flag(Integer is_flag) {
        this.is_flag = is_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.dapt_remark
     *
     * @return the value of mon_department_info.dapt_remark
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public String getDapt_remark() {
        return dapt_remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.dapt_remark
     *
     * @param dapt_remark the value for mon_department_info.dapt_remark
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setDapt_remark(String dapt_remark) {
        this.dapt_remark = dapt_remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.gs_id
     *
     * @return the value of mon_department_info.gs_id
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public Integer getGs_id() {
        return gs_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.gs_id
     *
     * @param gs_id the value for mon_department_info.gs_id
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setGs_id(Integer gs_id) {
        this.gs_id = gs_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.pt_id
     *
     * @return the value of mon_department_info.pt_id
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public Integer getPt_id() {
        return pt_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.pt_id
     *
     * @param pt_id the value for mon_department_info.pt_id
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setPt_id(Integer pt_id) {
        this.pt_id = pt_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.fw_type
     *
     * @return the value of mon_department_info.fw_type
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public Integer getFw_type() {
        return fw_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.fw_type
     *
     * @param fw_type the value for mon_department_info.fw_type
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setFw_type(Integer fw_type) {
        this.fw_type = fw_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.dept_super_ids
     *
     * @return the value of mon_department_info.dept_super_ids
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public String getDept_super_ids() {
        return dept_super_ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.dept_super_ids
     *
     * @param dept_super_ids the value for mon_department_info.dept_super_ids
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setDept_super_ids(String dept_super_ids) {
        this.dept_super_ids = dept_super_ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.name
     *
     * @return the value of mon_department_info.name
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.name
     *
     * @param name the value for mon_department_info.name
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.color
     *
     * @return the value of mon_department_info.color
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.color
     *
     * @param color the value for mon_department_info.color
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.qy_id
     *
     * @return the value of mon_department_info.qy_id
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public Integer getQy_id() {
        return qy_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.qy_id
     *
     * @param qy_id the value for mon_department_info.qy_id
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setQy_id(Integer qy_id) {
        this.qy_id = qy_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.orgcoding
     *
     * @return the value of mon_department_info.orgcoding
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public String getOrgcoding() {
        return orgcoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.orgcoding
     *
     * @param orgcoding the value for mon_department_info.orgcoding
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setOrgcoding(String orgcoding) {
        this.orgcoding = orgcoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.orgallname
     *
     * @return the value of mon_department_info.orgallname
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public String getOrgallname() {
        return orgallname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.orgallname
     *
     * @param orgallname the value for mon_department_info.orgallname
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setOrgallname(String orgallname) {
        this.orgallname = orgallname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.dept_flag
     *
     * @return the value of mon_department_info.dept_flag
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public Integer getDept_flag() {
        return dept_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.dept_flag
     *
     * @param dept_flag the value for mon_department_info.dept_flag
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setDept_flag(Integer dept_flag) {
        this.dept_flag = dept_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.dept_number
     *
     * @return the value of mon_department_info.dept_number
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public String getDept_number() {
        return dept_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.dept_number
     *
     * @param dept_number the value for mon_department_info.dept_number
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setDept_number(String dept_number) {
        this.dept_number = dept_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.syna_time
     *
     * @return the value of mon_department_info.syna_time
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public Date getSyna_time() {
        return syna_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.syna_time
     *
     * @param syna_time the value for mon_department_info.syna_time
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setSyna_time(Date syna_time) {
        this.syna_time = syna_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.syna_flag
     *
     * @return the value of mon_department_info.syna_flag
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public String getSyna_flag() {
        return syna_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.syna_flag
     *
     * @param syna_flag the value for mon_department_info.syna_flag
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setSyna_flag(String syna_flag) {
        this.syna_flag = syna_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_department_info.geo
     *
     * @return the value of mon_department_info.geo
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public String getGeo() {
        return geo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_department_info.geo
     *
     * @param geo the value for mon_department_info.geo
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    public void setGeo(String geo) {
        this.geo = geo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_department_info
     *
     * @mbggenerated Sun Sep 30 14:42:16 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", dept_name=").append(dept_name);
        sb.append(", dept_type=").append(dept_type);
        sb.append(", dept_super_id=").append(dept_super_id);
        sb.append(", dept_desc=").append(dept_desc);
        sb.append(", dept_lat=").append(dept_lat);
        sb.append(", dept_lon=").append(dept_lon);
        sb.append(", dept_adress=").append(dept_adress);
        sb.append(", is_flag=").append(is_flag);
        sb.append(", dapt_remark=").append(dapt_remark);
        sb.append(", gs_id=").append(gs_id);
        sb.append(", pt_id=").append(pt_id);
        sb.append(", fw_type=").append(fw_type);
        sb.append(", dept_super_ids=").append(dept_super_ids);
        sb.append(", name=").append(name);
        sb.append(", color=").append(color);
        sb.append(", qy_id=").append(qy_id);
        sb.append(", orgcoding=").append(orgcoding);
        sb.append(", orgallname=").append(orgallname);
        sb.append(", dept_flag=").append(dept_flag);
        sb.append(", dept_number=").append(dept_number);
        sb.append(", syna_time=").append(syna_time);
        sb.append(", syna_flag=").append(syna_flag);
        sb.append(", geo=").append(geo);
        sb.append("]");
        return sb.toString();
    }
}