package com.github.kyrenesjtv.springboot2.springboot2_withsql.po;

public class MonOperationInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_operation_info.id
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_operation_info.old_id
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    private Integer old_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_operation_info.operation
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    private String operation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_operation_info.table_name
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    private String table_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_operation_info.id
     *
     * @return the value of mon_operation_info.id
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_operation_info.id
     *
     * @param id the value for mon_operation_info.id
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_operation_info.old_id
     *
     * @return the value of mon_operation_info.old_id
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    public Integer getOld_id() {
        return old_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_operation_info.old_id
     *
     * @param old_id the value for mon_operation_info.old_id
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    public void setOld_id(Integer old_id) {
        this.old_id = old_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_operation_info.operation
     *
     * @return the value of mon_operation_info.operation
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_operation_info.operation
     *
     * @param operation the value for mon_operation_info.operation
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    public void setOperation(String operation) {
        this.operation = operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_operation_info.table_name
     *
     * @return the value of mon_operation_info.table_name
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    public String getTable_name() {
        return table_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_operation_info.table_name
     *
     * @param table_name the value for mon_operation_info.table_name
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    public void setTable_name(String table_name) {
        this.table_name = table_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_operation_info
     *
     * @mbggenerated Sat Sep 29 16:31:27 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", old_id=").append(old_id);
        sb.append(", operation=").append(operation);
        sb.append(", table_name=").append(table_name);
        sb.append("]");
        return sb.toString();
    }
}