package com.github.kyrenesjtv.springboot2.springboot2_withsql.po;

import java.util.Date;

public class MonUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.user_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String user_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.user_past_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date user_past_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.user_pwd
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String user_pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.user_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer user_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.user_state
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer user_state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.user_dept_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer user_dept_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.user_phone_login
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer user_phone_login;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.role_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer role_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.user_remark
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String user_remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.user_sex
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer user_sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.user_phone
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String user_phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.user_address
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String user_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.user_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String user_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.is_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer is_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.user_img_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String user_img_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.user_img_path
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String user_img_path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.is_flag
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer is_flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.user_car_cj
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String user_car_cj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.driverType
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer driverType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.user_alertyear
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String user_alertyear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.user_is_cg
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer user_is_cg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.driver_img_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String driver_img_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.driver_ddimg_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String driver_ddimg_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.driver_phone_duanhao
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String driver_phone_duanhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.driver_jiashizheng_date
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date driver_jiashizheng_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.driver_zhunjia
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer driver_zhunjia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.driver_num_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date driver_num_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.driver_time_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer driver_time_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.vacate_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer vacate_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.vacate_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer vacate_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.drivercard_jieshu_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date drivercard_jieshu_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.driver_niansheng
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer driver_niansheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.driver_age
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer driver_age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.driver_zjcx
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String driver_zjcx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.driver_number
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String driver_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.driver_check_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date driver_check_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.driverFp
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer driverFp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.driver_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Integer driver_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.bianzhi
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String bianzhi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.chedui
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String chedui;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.uname
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.sso_user_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String sso_user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.sf_no
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String sf_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.csny_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date csny_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.mz
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String mz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.jg
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String jg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.zzmm
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String zzmm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.rdsj
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date rdsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.hyzk
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String hyzk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.cjgzsj
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date cjgzsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.jbdwsj
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date jbdwsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.xqrzw
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String xqrzw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.xl_q
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String xl_q;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.xw_q
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String xw_q;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.yx_zy_q
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String yx_zy_q;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.xl_z
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String xl_z;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.xw_z
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String xw_z;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.yx_zy_z
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String yx_zy_z;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.bz_sf
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String bz_sf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.dj_zw
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String dj_zw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.fjszd
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String fjszd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.tbrq
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date tbrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.ujstsettings
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String ujstsettings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.syna_flag
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String syna_flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.city_code
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private String city_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.old_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Long old_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_user_info.syna_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    private Date syna_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.id
     *
     * @return the value of mon_user_info.id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.id
     *
     * @param id the value for mon_user_info.id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.user_name
     *
     * @return the value of mon_user_info.user_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getUser_name() {
        return user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.user_name
     *
     * @param user_name the value for mon_user_info.user_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.user_past_time
     *
     * @return the value of mon_user_info.user_past_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getUser_past_time() {
        return user_past_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.user_past_time
     *
     * @param user_past_time the value for mon_user_info.user_past_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setUser_past_time(Date user_past_time) {
        this.user_past_time = user_past_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.user_pwd
     *
     * @return the value of mon_user_info.user_pwd
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getUser_pwd() {
        return user_pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.user_pwd
     *
     * @param user_pwd the value for mon_user_info.user_pwd
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setUser_pwd(String user_pwd) {
        this.user_pwd = user_pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.user_type
     *
     * @return the value of mon_user_info.user_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getUser_type() {
        return user_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.user_type
     *
     * @param user_type the value for mon_user_info.user_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setUser_type(Integer user_type) {
        this.user_type = user_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.user_state
     *
     * @return the value of mon_user_info.user_state
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getUser_state() {
        return user_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.user_state
     *
     * @param user_state the value for mon_user_info.user_state
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setUser_state(Integer user_state) {
        this.user_state = user_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.user_dept_id
     *
     * @return the value of mon_user_info.user_dept_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getUser_dept_id() {
        return user_dept_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.user_dept_id
     *
     * @param user_dept_id the value for mon_user_info.user_dept_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setUser_dept_id(Integer user_dept_id) {
        this.user_dept_id = user_dept_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.user_phone_login
     *
     * @return the value of mon_user_info.user_phone_login
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getUser_phone_login() {
        return user_phone_login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.user_phone_login
     *
     * @param user_phone_login the value for mon_user_info.user_phone_login
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setUser_phone_login(Integer user_phone_login) {
        this.user_phone_login = user_phone_login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.role_id
     *
     * @return the value of mon_user_info.role_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getRole_id() {
        return role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.role_id
     *
     * @param role_id the value for mon_user_info.role_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setRole_id(Integer role_id) {
        this.role_id = role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.user_remark
     *
     * @return the value of mon_user_info.user_remark
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getUser_remark() {
        return user_remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.user_remark
     *
     * @param user_remark the value for mon_user_info.user_remark
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setUser_remark(String user_remark) {
        this.user_remark = user_remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.user_sex
     *
     * @return the value of mon_user_info.user_sex
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getUser_sex() {
        return user_sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.user_sex
     *
     * @param user_sex the value for mon_user_info.user_sex
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setUser_sex(Integer user_sex) {
        this.user_sex = user_sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.user_phone
     *
     * @return the value of mon_user_info.user_phone
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getUser_phone() {
        return user_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.user_phone
     *
     * @param user_phone the value for mon_user_info.user_phone
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setUser_phone(String user_phone) {
        this.user_phone = user_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.user_address
     *
     * @return the value of mon_user_info.user_address
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getUser_address() {
        return user_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.user_address
     *
     * @param user_address the value for mon_user_info.user_address
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setUser_address(String user_address) {
        this.user_address = user_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.user_num
     *
     * @return the value of mon_user_info.user_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getUser_num() {
        return user_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.user_num
     *
     * @param user_num the value for mon_user_info.user_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setUser_num(String user_num) {
        this.user_num = user_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.is_type
     *
     * @return the value of mon_user_info.is_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getIs_type() {
        return is_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.is_type
     *
     * @param is_type the value for mon_user_info.is_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setIs_type(Integer is_type) {
        this.is_type = is_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.user_img_name
     *
     * @return the value of mon_user_info.user_img_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getUser_img_name() {
        return user_img_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.user_img_name
     *
     * @param user_img_name the value for mon_user_info.user_img_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setUser_img_name(String user_img_name) {
        this.user_img_name = user_img_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.user_img_path
     *
     * @return the value of mon_user_info.user_img_path
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getUser_img_path() {
        return user_img_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.user_img_path
     *
     * @param user_img_path the value for mon_user_info.user_img_path
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setUser_img_path(String user_img_path) {
        this.user_img_path = user_img_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.is_flag
     *
     * @return the value of mon_user_info.is_flag
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getIs_flag() {
        return is_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.is_flag
     *
     * @param is_flag the value for mon_user_info.is_flag
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setIs_flag(Integer is_flag) {
        this.is_flag = is_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.user_car_cj
     *
     * @return the value of mon_user_info.user_car_cj
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getUser_car_cj() {
        return user_car_cj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.user_car_cj
     *
     * @param user_car_cj the value for mon_user_info.user_car_cj
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setUser_car_cj(String user_car_cj) {
        this.user_car_cj = user_car_cj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.driverType
     *
     * @return the value of mon_user_info.driverType
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getDriverType() {
        return driverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.driverType
     *
     * @param driverType the value for mon_user_info.driverType
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDriverType(Integer driverType) {
        this.driverType = driverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.user_alertyear
     *
     * @return the value of mon_user_info.user_alertyear
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getUser_alertyear() {
        return user_alertyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.user_alertyear
     *
     * @param user_alertyear the value for mon_user_info.user_alertyear
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setUser_alertyear(String user_alertyear) {
        this.user_alertyear = user_alertyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.user_is_cg
     *
     * @return the value of mon_user_info.user_is_cg
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getUser_is_cg() {
        return user_is_cg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.user_is_cg
     *
     * @param user_is_cg the value for mon_user_info.user_is_cg
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setUser_is_cg(Integer user_is_cg) {
        this.user_is_cg = user_is_cg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.driver_img_name
     *
     * @return the value of mon_user_info.driver_img_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getDriver_img_name() {
        return driver_img_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.driver_img_name
     *
     * @param driver_img_name the value for mon_user_info.driver_img_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDriver_img_name(String driver_img_name) {
        this.driver_img_name = driver_img_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.driver_ddimg_name
     *
     * @return the value of mon_user_info.driver_ddimg_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getDriver_ddimg_name() {
        return driver_ddimg_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.driver_ddimg_name
     *
     * @param driver_ddimg_name the value for mon_user_info.driver_ddimg_name
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDriver_ddimg_name(String driver_ddimg_name) {
        this.driver_ddimg_name = driver_ddimg_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.driver_phone_duanhao
     *
     * @return the value of mon_user_info.driver_phone_duanhao
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getDriver_phone_duanhao() {
        return driver_phone_duanhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.driver_phone_duanhao
     *
     * @param driver_phone_duanhao the value for mon_user_info.driver_phone_duanhao
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDriver_phone_duanhao(String driver_phone_duanhao) {
        this.driver_phone_duanhao = driver_phone_duanhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.driver_jiashizheng_date
     *
     * @return the value of mon_user_info.driver_jiashizheng_date
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getDriver_jiashizheng_date() {
        return driver_jiashizheng_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.driver_jiashizheng_date
     *
     * @param driver_jiashizheng_date the value for mon_user_info.driver_jiashizheng_date
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDriver_jiashizheng_date(Date driver_jiashizheng_date) {
        this.driver_jiashizheng_date = driver_jiashizheng_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.driver_zhunjia
     *
     * @return the value of mon_user_info.driver_zhunjia
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getDriver_zhunjia() {
        return driver_zhunjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.driver_zhunjia
     *
     * @param driver_zhunjia the value for mon_user_info.driver_zhunjia
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDriver_zhunjia(Integer driver_zhunjia) {
        this.driver_zhunjia = driver_zhunjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.driver_num_time
     *
     * @return the value of mon_user_info.driver_num_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getDriver_num_time() {
        return driver_num_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.driver_num_time
     *
     * @param driver_num_time the value for mon_user_info.driver_num_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDriver_num_time(Date driver_num_time) {
        this.driver_num_time = driver_num_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.driver_time_num
     *
     * @return the value of mon_user_info.driver_time_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getDriver_time_num() {
        return driver_time_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.driver_time_num
     *
     * @param driver_time_num the value for mon_user_info.driver_time_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDriver_time_num(Integer driver_time_num) {
        this.driver_time_num = driver_time_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.vacate_id
     *
     * @return the value of mon_user_info.vacate_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getVacate_id() {
        return vacate_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.vacate_id
     *
     * @param vacate_id the value for mon_user_info.vacate_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setVacate_id(Integer vacate_id) {
        this.vacate_id = vacate_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.vacate_num
     *
     * @return the value of mon_user_info.vacate_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getVacate_num() {
        return vacate_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.vacate_num
     *
     * @param vacate_num the value for mon_user_info.vacate_num
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setVacate_num(Integer vacate_num) {
        this.vacate_num = vacate_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.drivercard_jieshu_time
     *
     * @return the value of mon_user_info.drivercard_jieshu_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getDrivercard_jieshu_time() {
        return drivercard_jieshu_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.drivercard_jieshu_time
     *
     * @param drivercard_jieshu_time the value for mon_user_info.drivercard_jieshu_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDrivercard_jieshu_time(Date drivercard_jieshu_time) {
        this.drivercard_jieshu_time = drivercard_jieshu_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.driver_niansheng
     *
     * @return the value of mon_user_info.driver_niansheng
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getDriver_niansheng() {
        return driver_niansheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.driver_niansheng
     *
     * @param driver_niansheng the value for mon_user_info.driver_niansheng
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDriver_niansheng(Integer driver_niansheng) {
        this.driver_niansheng = driver_niansheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.driver_age
     *
     * @return the value of mon_user_info.driver_age
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getDriver_age() {
        return driver_age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.driver_age
     *
     * @param driver_age the value for mon_user_info.driver_age
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDriver_age(Integer driver_age) {
        this.driver_age = driver_age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.driver_zjcx
     *
     * @return the value of mon_user_info.driver_zjcx
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getDriver_zjcx() {
        return driver_zjcx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.driver_zjcx
     *
     * @param driver_zjcx the value for mon_user_info.driver_zjcx
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDriver_zjcx(String driver_zjcx) {
        this.driver_zjcx = driver_zjcx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.driver_number
     *
     * @return the value of mon_user_info.driver_number
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getDriver_number() {
        return driver_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.driver_number
     *
     * @param driver_number the value for mon_user_info.driver_number
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDriver_number(String driver_number) {
        this.driver_number = driver_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.driver_check_time
     *
     * @return the value of mon_user_info.driver_check_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getDriver_check_time() {
        return driver_check_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.driver_check_time
     *
     * @param driver_check_time the value for mon_user_info.driver_check_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDriver_check_time(Date driver_check_time) {
        this.driver_check_time = driver_check_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.driverFp
     *
     * @return the value of mon_user_info.driverFp
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getDriverFp() {
        return driverFp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.driverFp
     *
     * @param driverFp the value for mon_user_info.driverFp
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDriverFp(Integer driverFp) {
        this.driverFp = driverFp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.driver_type
     *
     * @return the value of mon_user_info.driver_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Integer getDriver_type() {
        return driver_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.driver_type
     *
     * @param driver_type the value for mon_user_info.driver_type
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDriver_type(Integer driver_type) {
        this.driver_type = driver_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.bianzhi
     *
     * @return the value of mon_user_info.bianzhi
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getBianzhi() {
        return bianzhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.bianzhi
     *
     * @param bianzhi the value for mon_user_info.bianzhi
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setBianzhi(String bianzhi) {
        this.bianzhi = bianzhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.chedui
     *
     * @return the value of mon_user_info.chedui
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getChedui() {
        return chedui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.chedui
     *
     * @param chedui the value for mon_user_info.chedui
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setChedui(String chedui) {
        this.chedui = chedui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.uname
     *
     * @return the value of mon_user_info.uname
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.uname
     *
     * @param uname the value for mon_user_info.uname
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.sso_user_id
     *
     * @return the value of mon_user_info.sso_user_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getSso_user_id() {
        return sso_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.sso_user_id
     *
     * @param sso_user_id the value for mon_user_info.sso_user_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setSso_user_id(String sso_user_id) {
        this.sso_user_id = sso_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.sf_no
     *
     * @return the value of mon_user_info.sf_no
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getSf_no() {
        return sf_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.sf_no
     *
     * @param sf_no the value for mon_user_info.sf_no
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setSf_no(String sf_no) {
        this.sf_no = sf_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.csny_time
     *
     * @return the value of mon_user_info.csny_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getCsny_time() {
        return csny_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.csny_time
     *
     * @param csny_time the value for mon_user_info.csny_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCsny_time(Date csny_time) {
        this.csny_time = csny_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.mz
     *
     * @return the value of mon_user_info.mz
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getMz() {
        return mz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.mz
     *
     * @param mz the value for mon_user_info.mz
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setMz(String mz) {
        this.mz = mz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.jg
     *
     * @return the value of mon_user_info.jg
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getJg() {
        return jg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.jg
     *
     * @param jg the value for mon_user_info.jg
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setJg(String jg) {
        this.jg = jg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.zzmm
     *
     * @return the value of mon_user_info.zzmm
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getZzmm() {
        return zzmm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.zzmm
     *
     * @param zzmm the value for mon_user_info.zzmm
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setZzmm(String zzmm) {
        this.zzmm = zzmm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.rdsj
     *
     * @return the value of mon_user_info.rdsj
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getRdsj() {
        return rdsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.rdsj
     *
     * @param rdsj the value for mon_user_info.rdsj
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setRdsj(Date rdsj) {
        this.rdsj = rdsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.hyzk
     *
     * @return the value of mon_user_info.hyzk
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getHyzk() {
        return hyzk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.hyzk
     *
     * @param hyzk the value for mon_user_info.hyzk
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setHyzk(String hyzk) {
        this.hyzk = hyzk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.cjgzsj
     *
     * @return the value of mon_user_info.cjgzsj
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getCjgzsj() {
        return cjgzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.cjgzsj
     *
     * @param cjgzsj the value for mon_user_info.cjgzsj
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCjgzsj(Date cjgzsj) {
        this.cjgzsj = cjgzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.jbdwsj
     *
     * @return the value of mon_user_info.jbdwsj
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getJbdwsj() {
        return jbdwsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.jbdwsj
     *
     * @param jbdwsj the value for mon_user_info.jbdwsj
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setJbdwsj(Date jbdwsj) {
        this.jbdwsj = jbdwsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.xqrzw
     *
     * @return the value of mon_user_info.xqrzw
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getXqrzw() {
        return xqrzw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.xqrzw
     *
     * @param xqrzw the value for mon_user_info.xqrzw
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setXqrzw(String xqrzw) {
        this.xqrzw = xqrzw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.xl_q
     *
     * @return the value of mon_user_info.xl_q
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getXl_q() {
        return xl_q;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.xl_q
     *
     * @param xl_q the value for mon_user_info.xl_q
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setXl_q(String xl_q) {
        this.xl_q = xl_q;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.xw_q
     *
     * @return the value of mon_user_info.xw_q
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getXw_q() {
        return xw_q;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.xw_q
     *
     * @param xw_q the value for mon_user_info.xw_q
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setXw_q(String xw_q) {
        this.xw_q = xw_q;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.yx_zy_q
     *
     * @return the value of mon_user_info.yx_zy_q
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getYx_zy_q() {
        return yx_zy_q;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.yx_zy_q
     *
     * @param yx_zy_q the value for mon_user_info.yx_zy_q
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setYx_zy_q(String yx_zy_q) {
        this.yx_zy_q = yx_zy_q;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.xl_z
     *
     * @return the value of mon_user_info.xl_z
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getXl_z() {
        return xl_z;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.xl_z
     *
     * @param xl_z the value for mon_user_info.xl_z
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setXl_z(String xl_z) {
        this.xl_z = xl_z;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.xw_z
     *
     * @return the value of mon_user_info.xw_z
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getXw_z() {
        return xw_z;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.xw_z
     *
     * @param xw_z the value for mon_user_info.xw_z
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setXw_z(String xw_z) {
        this.xw_z = xw_z;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.yx_zy_z
     *
     * @return the value of mon_user_info.yx_zy_z
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getYx_zy_z() {
        return yx_zy_z;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.yx_zy_z
     *
     * @param yx_zy_z the value for mon_user_info.yx_zy_z
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setYx_zy_z(String yx_zy_z) {
        this.yx_zy_z = yx_zy_z;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.bz_sf
     *
     * @return the value of mon_user_info.bz_sf
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getBz_sf() {
        return bz_sf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.bz_sf
     *
     * @param bz_sf the value for mon_user_info.bz_sf
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setBz_sf(String bz_sf) {
        this.bz_sf = bz_sf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.dj_zw
     *
     * @return the value of mon_user_info.dj_zw
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getDj_zw() {
        return dj_zw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.dj_zw
     *
     * @param dj_zw the value for mon_user_info.dj_zw
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setDj_zw(String dj_zw) {
        this.dj_zw = dj_zw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.fjszd
     *
     * @return the value of mon_user_info.fjszd
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getFjszd() {
        return fjszd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.fjszd
     *
     * @param fjszd the value for mon_user_info.fjszd
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setFjszd(String fjszd) {
        this.fjszd = fjszd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.tbrq
     *
     * @return the value of mon_user_info.tbrq
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getTbrq() {
        return tbrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.tbrq
     *
     * @param tbrq the value for mon_user_info.tbrq
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setTbrq(Date tbrq) {
        this.tbrq = tbrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.ujstsettings
     *
     * @return the value of mon_user_info.ujstsettings
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getUjstsettings() {
        return ujstsettings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.ujstsettings
     *
     * @param ujstsettings the value for mon_user_info.ujstsettings
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setUjstsettings(String ujstsettings) {
        this.ujstsettings = ujstsettings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.syna_flag
     *
     * @return the value of mon_user_info.syna_flag
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getSyna_flag() {
        return syna_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.syna_flag
     *
     * @param syna_flag the value for mon_user_info.syna_flag
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setSyna_flag(String syna_flag) {
        this.syna_flag = syna_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.city_code
     *
     * @return the value of mon_user_info.city_code
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public String getCity_code() {
        return city_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.city_code
     *
     * @param city_code the value for mon_user_info.city_code
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setCity_code(String city_code) {
        this.city_code = city_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.old_id
     *
     * @return the value of mon_user_info.old_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Long getOld_id() {
        return old_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.old_id
     *
     * @param old_id the value for mon_user_info.old_id
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setOld_id(Long old_id) {
        this.old_id = old_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_user_info.syna_time
     *
     * @return the value of mon_user_info.syna_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public Date getSyna_time() {
        return syna_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_user_info.syna_time
     *
     * @param syna_time the value for mon_user_info.syna_time
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    public void setSyna_time(Date syna_time) {
        this.syna_time = syna_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_user_info
     *
     * @mbggenerated Sat Sep 29 16:11:36 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", user_name=").append(user_name);
        sb.append(", user_past_time=").append(user_past_time);
        sb.append(", user_pwd=").append(user_pwd);
        sb.append(", user_type=").append(user_type);
        sb.append(", user_state=").append(user_state);
        sb.append(", user_dept_id=").append(user_dept_id);
        sb.append(", user_phone_login=").append(user_phone_login);
        sb.append(", role_id=").append(role_id);
        sb.append(", user_remark=").append(user_remark);
        sb.append(", user_sex=").append(user_sex);
        sb.append(", user_phone=").append(user_phone);
        sb.append(", user_address=").append(user_address);
        sb.append(", user_num=").append(user_num);
        sb.append(", is_type=").append(is_type);
        sb.append(", user_img_name=").append(user_img_name);
        sb.append(", user_img_path=").append(user_img_path);
        sb.append(", is_flag=").append(is_flag);
        sb.append(", user_car_cj=").append(user_car_cj);
        sb.append(", driverType=").append(driverType);
        sb.append(", user_alertyear=").append(user_alertyear);
        sb.append(", user_is_cg=").append(user_is_cg);
        sb.append(", driver_img_name=").append(driver_img_name);
        sb.append(", driver_ddimg_name=").append(driver_ddimg_name);
        sb.append(", driver_phone_duanhao=").append(driver_phone_duanhao);
        sb.append(", driver_jiashizheng_date=").append(driver_jiashizheng_date);
        sb.append(", driver_zhunjia=").append(driver_zhunjia);
        sb.append(", driver_num_time=").append(driver_num_time);
        sb.append(", driver_time_num=").append(driver_time_num);
        sb.append(", vacate_id=").append(vacate_id);
        sb.append(", vacate_num=").append(vacate_num);
        sb.append(", drivercard_jieshu_time=").append(drivercard_jieshu_time);
        sb.append(", driver_niansheng=").append(driver_niansheng);
        sb.append(", driver_age=").append(driver_age);
        sb.append(", driver_zjcx=").append(driver_zjcx);
        sb.append(", driver_number=").append(driver_number);
        sb.append(", driver_check_time=").append(driver_check_time);
        sb.append(", driverFp=").append(driverFp);
        sb.append(", driver_type=").append(driver_type);
        sb.append(", bianzhi=").append(bianzhi);
        sb.append(", chedui=").append(chedui);
        sb.append(", uname=").append(uname);
        sb.append(", sso_user_id=").append(sso_user_id);
        sb.append(", sf_no=").append(sf_no);
        sb.append(", csny_time=").append(csny_time);
        sb.append(", mz=").append(mz);
        sb.append(", jg=").append(jg);
        sb.append(", zzmm=").append(zzmm);
        sb.append(", rdsj=").append(rdsj);
        sb.append(", hyzk=").append(hyzk);
        sb.append(", cjgzsj=").append(cjgzsj);
        sb.append(", jbdwsj=").append(jbdwsj);
        sb.append(", xqrzw=").append(xqrzw);
        sb.append(", xl_q=").append(xl_q);
        sb.append(", xw_q=").append(xw_q);
        sb.append(", yx_zy_q=").append(yx_zy_q);
        sb.append(", xl_z=").append(xl_z);
        sb.append(", xw_z=").append(xw_z);
        sb.append(", yx_zy_z=").append(yx_zy_z);
        sb.append(", bz_sf=").append(bz_sf);
        sb.append(", dj_zw=").append(dj_zw);
        sb.append(", fjszd=").append(fjszd);
        sb.append(", tbrq=").append(tbrq);
        sb.append(", ujstsettings=").append(ujstsettings);
        sb.append(", syna_flag=").append(syna_flag);
        sb.append(", city_code=").append(city_code);
        sb.append(", old_id=").append(old_id);
        sb.append(", syna_time=").append(syna_time);
        sb.append("]");
        return sb.toString();
    }
}